# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: list
aliases:
    - ls
description: Print a list of configuration keys and values
flags:
    -h, --host=: Get per-host configuration
