# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: clear-cache
description: Clear the cli cache
documentation:
    command: >-
        Clear the CLI cache, removing locally stored data.
