package cmd

import (
	"github.com/carapace-sh/carapace"
	"github.com/carapace-sh/carapace-bin/pkg/actions/tools/uv"
	"github.com/spf13/cobra"
)

var pip_compileCmd = &cobra.Command{
	Use:   "compile",
	Short: "Compile a `requirements.in` file to a `requirements.txt` or `pylock.toml` file",
	Run:   func(cmd *cobra.Command, args []string) {},
}

func init() {
	carapace.Gen(pip_compileCmd).Standalone()

	pip_compileCmd.Flags().Bool("all-extras", false, "Include all optional dependencies")
	pip_compileCmd.Flags().Bool("allow-unsafe", false, "")
	pip_compileCmd.Flags().Bool("annotate", false, "")
	pip_compileCmd.Flags().String("annotation-style", "", "The style of the annotation comments included in the output file, used to indicate the source of each package")
	pip_compileCmd.Flags().Bool("build", false, "")
	pip_compileCmd.Flags().StringSlice("build-constraint", nil, "Constrain build dependencies using the given requirements files when building source distributions")
	pip_compileCmd.Flags().StringSliceP("build-constraints", "b", nil, "Constrain build dependencies using the given requirements files when building source distributions")
	pip_compileCmd.Flags().Bool("build-isolation", false, "")
	pip_compileCmd.Flags().String("client-cert", "", "")
	pip_compileCmd.Flags().String("config", "", "")
	pip_compileCmd.Flags().StringSliceP("config-setting", "C", nil, "Settings to pass to the PEP 517 build backend, specified as `KEY=VALUE` pairs")
	pip_compileCmd.Flags().StringSlice("config-settings", nil, "Settings to pass to the PEP 517 build backend, specified as `KEY=VALUE` pairs")
	pip_compileCmd.Flags().StringSlice("config-settings-package", nil, "Settings to pass to the PEP 517 build backend for a specific package, specified as `PACKAGE:KEY=VALUE` pairs")
	pip_compileCmd.Flags().StringSlice("constraint", nil, "Constrain versions using the given requirements files")
	pip_compileCmd.Flags().StringSliceP("constraints", "c", nil, "Constrain versions using the given requirements files")
	pip_compileCmd.Flags().String("custom-compile-command", "", "The header comment to include at the top of the output file generated by `uv pip compile`")
	pip_compileCmd.Flags().String("default-index", "", "The default package index (by default: <https://pypi.org/simple>)")
	pip_compileCmd.Flags().Bool("deps", false, "")
	pip_compileCmd.Flags().Bool("emit-build-options", false, "Include `--no-binary` and `--only-binary` entries in the generated output file")
	pip_compileCmd.Flags().Bool("emit-find-links", false, "Include `--find-links` entries in the generated output file")
	pip_compileCmd.Flags().Bool("emit-index-annotation", false, "Include comment annotations indicating the index used to resolve each package (e.g., `# from https://pypi.org/simple`)")
	pip_compileCmd.Flags().Bool("emit-index-url", false, "Include `--index-url` and `--extra-index-url` entries in the generated output file")
	pip_compileCmd.Flags().Bool("emit-marker-expression", false, "Whether to emit a marker string indicating when it is known that the resulting set of pinned dependencies is valid")
	pip_compileCmd.Flags().Bool("emit-options", false, "")
	pip_compileCmd.Flags().Bool("emit-trusted-host", false, "")
	pip_compileCmd.Flags().StringSlice("exclude", nil, "Exclude packages from resolution using the given requirements files")
	pip_compileCmd.Flags().String("exclude-newer", "", "Limit candidate packages to those that were uploaded prior to the given date")
	pip_compileCmd.Flags().StringSlice("exclude-newer-package", nil, "Limit candidate packages for specific packages to those that were uploaded prior to the given date")
	pip_compileCmd.Flags().StringSlice("excludes", nil, "Exclude packages from resolution using the given requirements files")
	pip_compileCmd.Flags().StringSlice("extra", nil, "Include optional dependencies from the specified extra name; may be provided more than once")
	pip_compileCmd.Flags().StringSlice("extra-index-url", nil, "(Deprecated: use `--index` instead) Extra URLs of package indexes to use, in addition to `--index-url`")
	pip_compileCmd.Flags().StringSliceP("find-links", "f", nil, "Locations to search for candidate distributions, in addition to those found in the registry indexes")
	pip_compileCmd.Flags().String("fork-strategy", "", "The strategy to use when selecting multiple versions of a given package across Python versions and platforms")
	pip_compileCmd.Flags().String("format", "", "The format in which the resolution should be output")
	pip_compileCmd.Flags().Bool("generate-hashes", false, "Include distribution hashes in the output file")
	pip_compileCmd.Flags().StringSlice("group", nil, "Install the specified dependency group from a `pyproject.toml`")
	pip_compileCmd.Flags().Bool("header", false, "")
	pip_compileCmd.Flags().StringSlice("index", nil, "The indexes to use when resolving dependencies, in addition to the default index")
	pip_compileCmd.Flags().String("index-strategy", "", "The strategy to use when resolving against multiple index URLs")
	pip_compileCmd.Flags().StringP("index-url", "i", "", "(Deprecated: use `--default-index` instead) The URL of the Python package index (by default: <https://pypi.org/simple>)")
	pip_compileCmd.Flags().String("keyring-provider", "", "Attempt to use `keyring` for authentication for index URLs")
	pip_compileCmd.Flags().String("link-mode", "", "The method to use when installing packages from the global cache")
	pip_compileCmd.Flags().String("max-rounds", "", "")
	pip_compileCmd.Flags().Bool("no-all-extras", false, "")
	pip_compileCmd.Flags().Bool("no-allow-unsafe", false, "")
	pip_compileCmd.Flags().Bool("no-annotate", false, "Exclude comment annotations indicating the source of each package")
	pip_compileCmd.Flags().StringSlice("no-binary", nil, "Don't install pre-built wheels")
	pip_compileCmd.Flags().Bool("no-build", false, "Don't build source distributions")
	pip_compileCmd.Flags().Bool("no-build-isolation", false, "Disable isolation when building source distributions")
	pip_compileCmd.Flags().StringSlice("no-build-isolation-package", nil, "Disable isolation when building source distributions for a specific package")
	pip_compileCmd.Flags().Bool("no-config", false, "")
	pip_compileCmd.Flags().Bool("no-deps", false, "Ignore package dependencies, instead only add those packages explicitly listed on the command line to the resulting requirements file")
	pip_compileCmd.Flags().Bool("no-emit-build-options", false, "")
	pip_compileCmd.Flags().Bool("no-emit-find-links", false, "")
	pip_compileCmd.Flags().Bool("no-emit-index-annotation", false, "")
	pip_compileCmd.Flags().Bool("no-emit-index-url", false, "")
	pip_compileCmd.Flags().Bool("no-emit-marker-expression", false, "")
	pip_compileCmd.Flags().Bool("no-emit-options", false, "")
	pip_compileCmd.Flags().StringSlice("no-emit-package", nil, "Specify a package to omit from the output resolution. Its dependencies will still be included in the resolution. Equivalent to pip-compile's `--unsafe-package` option")
	pip_compileCmd.Flags().Bool("no-emit-trusted-host", false, "")
	pip_compileCmd.Flags().Bool("no-generate-hashes", false, "")
	pip_compileCmd.Flags().Bool("no-header", false, "Exclude the comment header at the top of the generated output file")
	pip_compileCmd.Flags().Bool("no-index", false, "Ignore the registry index (e.g., PyPI), instead relying on direct URL dependencies and those provided via `--find-links`")
	pip_compileCmd.Flags().Bool("no-refresh", false, "")
	pip_compileCmd.Flags().Bool("no-reuse-hashes", false, "")
	pip_compileCmd.Flags().Bool("no-sources", false, "Ignore the `tool.uv.sources` table when resolving dependencies. Used to lock against the standards-compliant, publishable package metadata, as opposed to using any workspace, Git, URL, or local path sources")
	pip_compileCmd.Flags().StringSlice("no-sources-package", nil, "Don't use sources from the `tool.uv.sources` table for the specified packages [env: `UV_NO_SOURCES_PACKAGE`=]")
	pip_compileCmd.Flags().Bool("no-strip-extras", false, "Include extras in the output file")
	pip_compileCmd.Flags().Bool("no-strip-markers", false, "Include environment markers in the output file")
	pip_compileCmd.Flags().Bool("no-system", false, "")
	pip_compileCmd.Flags().Bool("no-universal", false, "")
	pip_compileCmd.Flags().Bool("no-upgrade", false, "")
	pip_compileCmd.Flags().StringSlice("only-binary", nil, "Only use pre-built wheels; don't build source distributions")
	pip_compileCmd.Flags().StringP("output-file", "o", "", "Write the compiled requirements to the given `requirements.txt` or `pylock.toml` file")
	pip_compileCmd.Flags().StringSlice("override", nil, "Override versions using the given requirements files")
	pip_compileCmd.Flags().StringSlice("overrides", nil, "Override versions using the given requirements files")
	pip_compileCmd.Flags().String("pip-args", "", "")
	pip_compileCmd.Flags().Bool("pre", false, "")
	pip_compileCmd.Flags().String("prerelease", "", "The strategy to use when considering pre-release versions")
	pip_compileCmd.Flags().StringSlice("prerelease-package", nil, "The strategy to use when considering pre-release versions for a specific package")
	pip_compileCmd.Flags().StringP("python", "p", "", "The Python interpreter to use during resolution.")
	pip_compileCmd.Flags().String("python-platform", "", "The platform for which requirements should be resolved")
	pip_compileCmd.Flags().String("python-version", "", "The Python version to use for resolution")
	pip_compileCmd.Flags().Bool("refresh", false, "Refresh all cached data")
	pip_compileCmd.Flags().StringSlice("refresh-package", nil, "Refresh cached data for a specific package")
	pip_compileCmd.Flags().String("resolution", "", "The strategy to use when selecting between the different compatible versions for a given package requirement")
	pip_compileCmd.Flags().String("resolver", "", "")
	pip_compileCmd.Flags().Bool("reuse-hashes", false, "")
	pip_compileCmd.Flags().Bool("strip-extras", false, "")
	pip_compileCmd.Flags().Bool("strip-markers", false, "")
	pip_compileCmd.Flags().Bool("system", false, "Install packages into the system Python environment")
	pip_compileCmd.Flags().String("torch-backend", "", "The backend to use when fetching packages in the PyTorch ecosystem (e.g., `cpu`, `cu126`, or `auto`)")
	pip_compileCmd.Flags().Bool("universal", false, "Perform a universal resolution, attempting to generate a single `requirements.txt` output file that is compatible with all operating systems, architectures, and Python implementations")
	pip_compileCmd.Flags().StringSlice("unsafe-package", nil, "Specify a package to omit from the output resolution. Its dependencies will still be included in the resolution. Equivalent to pip-compile's `--unsafe-package` option")
	pip_compileCmd.Flags().BoolP("upgrade", "U", false, "Allow package upgrades, ignoring pinned versions in any existing output file. Implies `--refresh`")
	pip_compileCmd.Flags().StringSlice("upgrade-group", nil, "Allow upgrades for all packages in a dependency group, ignoring pinned versions in any existing output file")
	pip_compileCmd.Flags().StringSliceP("upgrade-package", "P", nil, "Allow upgrades for a specific package, ignoring pinned versions in any existing output file. Implies `--refresh-package`")

	pip_compileCmd.Flag("allow-unsafe").Hidden = true
	pip_compileCmd.Flag("annotate").Hidden = true
	pip_compileCmd.Flag("build").Hidden = true
	pip_compileCmd.Flag("build-constraint").Hidden = true
	pip_compileCmd.Flag("build-isolation").Hidden = true
	pip_compileCmd.Flag("client-cert").Hidden = true
	pip_compileCmd.Flag("config").Hidden = true
	pip_compileCmd.Flag("config-settings").Hidden = true
	pip_compileCmd.Flag("constraint").Hidden = true
	pip_compileCmd.Flag("deps").Hidden = true
	pip_compileCmd.Flag("emit-marker-expression").Hidden = true
	pip_compileCmd.Flag("emit-options").Hidden = true
	pip_compileCmd.Flag("emit-trusted-host").Hidden = true
	pip_compileCmd.Flag("exclude").Hidden = true
	pip_compileCmd.Flag("header").Hidden = true
	pip_compileCmd.Flag("max-rounds").Hidden = true
	pip_compileCmd.Flag("no-all-extras").Hidden = true
	pip_compileCmd.Flag("no-allow-unsafe").Hidden = true
	pip_compileCmd.Flag("no-config").Hidden = true
	pip_compileCmd.Flag("no-emit-build-options").Hidden = true
	pip_compileCmd.Flag("no-emit-find-links").Hidden = true
	pip_compileCmd.Flag("no-emit-index-annotation").Hidden = true
	pip_compileCmd.Flag("no-emit-index-url").Hidden = true
	pip_compileCmd.Flag("no-emit-marker-expression").Hidden = true
	pip_compileCmd.Flag("no-emit-options").Hidden = true
	pip_compileCmd.Flag("no-emit-trusted-host").Hidden = true
	pip_compileCmd.Flag("no-generate-hashes").Hidden = true
	pip_compileCmd.Flag("no-refresh").Hidden = true
	pip_compileCmd.Flag("no-reuse-hashes").Hidden = true
	pip_compileCmd.Flag("no-system").Hidden = true
	pip_compileCmd.Flag("no-universal").Hidden = true
	pip_compileCmd.Flag("no-upgrade").Hidden = true
	pip_compileCmd.Flag("override").Hidden = true
	pip_compileCmd.Flag("pip-args").Hidden = true
	pip_compileCmd.Flag("pre").Hidden = true
	pip_compileCmd.Flag("resolver").Hidden = true
	pip_compileCmd.Flag("reuse-hashes").Hidden = true
	pip_compileCmd.Flag("strip-extras").Hidden = true
	pip_compileCmd.Flag("strip-markers").Hidden = true
	pip_compileCmd.Flag("unsafe-package").Hidden = true

	pipCmd.AddCommand(pip_compileCmd)

	carapace.Gen(pip_compileCmd).FlagCompletion(carapace.ActionMap{
		"annotation-style": carapace.ActionValuesDescribed(
			"line", "Render the annotations on a single, comma-separated line",
			"split", "Render each annotation on its own line",
		),
		"build-constraint":  carapace.ActionFiles(),
		"build-constraints": carapace.ActionFiles(),
		"constraint":        carapace.ActionFiles(),
		"constraints":       carapace.ActionFiles(),
		"exclude":           carapace.ActionFiles(),
		"excludes":          carapace.ActionFiles(),
		"extra":             uv.ActionExtras(),
		"fork-strategy":     uv.ActionForkStrategies(),
		"format": carapace.ActionValuesDescribed(
			"requirements.txt", "Export in `requirements.txt` format",
			"pylock.toml", "Export in `pylock.toml` format",
		),
		"group":            uv.ActionDependencyGroups(),
		"index-strategy":   uv.ActionIndexStrategies(),
		"keyring-provider": uv.ActionKeyringProviders(),
		"link-mode":        uv.ActionLinkModes(),
		"output-file":      carapace.ActionFiles(),
		"override":         carapace.ActionFiles(),
		"overrides":        carapace.ActionFiles(),
		"prerelease":       uv.ActionPreReleases(),
		"python":           uv.ActionPythonInstallations(uv.InstallationsOpts{}),
		"python-platform":  uv.ActionPythonPlatforms(),
		"resolution":       uv.ActionResolutions(),
		"resolver": carapace.ActionValues(
			"backtracking",
			"legacy",
		),
		"torch-backend": uv.ActionTorchBackends(),
	})

	carapace.Gen(pip_compileCmd).PositionalAnyCompletion(carapace.ActionFiles())
}
