# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: remove [options] <group-spec|environment-spec>...
description: remove environments
flags:
    --no-packages: operate on environments without manipulating packages
    --with-optional: include optional packages
