# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: validate
description: Check that the config file is well formed.
flags:
    -o, --org-slug=: 'organization slug (for example: github/example-org), used when a config depends on private orbs belonging to that org'
persistentflags:
    -c, --config=: path to config file
