before:
  hooks:
    - go mod download
    - go generate ./cmd/...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/carapace
    binary: carapace
    tags:
      - release
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "carapace-bin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: carapace
    description: "multi-shell multi-command argument completer"
    homepage: "https://github.com/rsteube/carapace-bin"
    license: "MIT"
    tap:
      owner: rsteube
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
scoop:
  description: "multi-shell multi-command argument completer"
  homepage: "https://github.com/rsteube/carapace-bin"
  license: "MIT"
  bucket:
    owner: rsteube
    name: scoop-bucket
    token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
aurs:
  -
    description: "multi-shell multi-command argument completer"
    homepage: "https://github.com/rsteube/carapace-bin"
    license: "MIT"
    maintainers:
      - rsteube <rsteube@users.noreply.github.com>
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/carapace-bin.git'
    provides:
      - carapace
    conflicts:
      - carapace

nfpms:
  -
    description: "multi-shell multi-command argument completer"
    homepage: "https://github.com/rsteube/carapace-bin"
    license: "MIT"
    maintainer: rsteube <rsteube@users.noreply.github.com>
    formats:
      - apk
      - deb
      - rpm

publishers:
  - name: fury
    cmd: "bash -c \"[[ {{.ArtifactPath}} =~ ^.*.(deb|rpm)$ ]] && curl -F package=@{{abs .ArtifactPath}} https://$FURY_TOKEN@push.fury.io/rsteube/ || true\""
    env:
      - FURY_TOKEN={{ .Env.FURY_TOKEN }}
