FROM mcr.microsoft.com/powershell

RUN mkdir -p /root/.config/powershell \
 && echo "\n\
function prompt {Write-Host \"carapace\" -NoNewLine -ForegroundColor 3; return \" \"}\n\
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete\n\
example _carapace powershell | out-string | Invoke-Expression" \
       > /root/.config/powershell/Microsoft.PowerShell_profile.ps1

RUN ln -s /carapace-completers/carapace-completers /usr/local/bin/carapace-completers

