FROM golang

RUN curl https://dl.elv.sh/linux-amd64/elvish-v0.14.1.tar.gz | tar -xvz \
 && mv elvish-* /usr/local/bin/elvish

ENV PS1=$'%{\e[0;36m%}carapace %{\e[0m%}'

RUN ln -s /carapace-completers/carapace/carapace /usr/local/bin/carapace

RUN mkdir -p /root/.elvish/lib \
 && echo "\
carapace _carapace elvish > /root/.elvish/lib/carapace.elv\n\
use carapace\n\
carapace --list | each [c]{ carapace \$c > /tmp/\$c; -source /tmp/\$c }" \
  > /root/.elvish/rc.elv

ENTRYPOINT [ "elvish" ]

