# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Read and write configuration settings
flags:
    --read-only: Operate in read-only mode.
    -a, --all: Show all configuration options.
    -h, --help: show this help message and exit
