package action

import "github.com/carapace-sh/carapace"

func ActionStandards() carapace.Action {
	return carapace.ActionValuesDescribed(
		"c89", "ISO C89",
		"c90", "ISO C90",
		"c99", "ISO C99",
		"c11", "ISO C11",
		"c17", "ISO C17",
		"c18", "ISO C18 (same as -std=c17)",
		"c23", "ISO C23",
		"c2y", "Working draft for C2Y",
		"gnu89", "GNU C89",
		"gnu90", "GNU C90",
		"gnu99", "GNU C99",
		"gnu11", "GNU C11",
		"gnu17", "GNU C17",
		"gnu18", "GNU C18 (same as -std=gnu17)",
		"gnu23", "GNU C23",
		"gnu2y", "GNU C2Y",
		"c++98", "ISO C++98",
		"c++03", "ISO C++03",
		"c++11", "ISO C++11",
		"c++14", "ISO C++14",
		"c++17", "ISO C++17",
		"c++20", "ISO C++20",
		"c++23", "ISO C++23",
		"c++26", "ISO C++26",
		"gnu++98", "GNU C++98",
		"gnu++03", "GNU C++03",
		"gnu++11", "GNU C++11",
		"gnu++14", "GNU C++14",
		"gnu++17", "GNU C++17",
		"gnu++20", "GNU C++20",
		"gnu++23", "GNU C++23",
		"gnu++26", "GNU C++26",
		"f95", "ISO Fortran 95",
		"f2003", "ISO Fortran 2003",
		"f2008", "ISO Fortran 2008",
		"f2018", "ISO Fortran 2018",
		"f2023", "ISO Fortran 2023",
		"gnu", "GNU default",
		"legacy", "Legacy",
		"d2024", "D language 2024 edition",
		"gnu68", "GNU Algol 68",
	)
}

func ActionLanguages() carapace.Action {
	return carapace.ActionValuesDescribed(
		"c", "C",
		"c++", "C++",
		"assembler", "Assembly",
		"none", "Revert to guessing based on file extension",
	)
}

func ActionCPUs() carapace.Action {
	return carapace.ActionValues(
		"native", "generic",
		"i386", "i486", "i586", "i686", "pentium",
		"pentium-mmx", "pentiumpro", "pentium2", "pentium3", "pentium4",
		"pentium-m", "pentium3m", "pentium4m",
		"prescott", "nocona", "core2", "nehalem", "corei7",
		"westmere", "sandybridge", "ivybridge", "haswell", "broadwell",
		"skylake", "skylake-avx512", "cannonlake", "icelake-client", "icelake-server",
		"cascadelake", "tigerlake", "cooperlake", "sapphirerapids", "emeraldrapids",
		"alderlake", "raptorlake", "meteorlake", "graniterapids", "graniterapids-d",
		"arrowlake", "arrowlake-s", "lunarlake", "pantherlake", "diamondrapids",
		"wildcatlake", "novalake",
		"bonnell", "atom", "silvermont", "slm", "goldmont", "goldmont-plus",
		"tremont", "gracemont", "sierraforest", "grandridge", "clearwaterforest",
		"lakemont",
		"geode", "k6", "k6-2", "k6-3",
		"athlon", "athlon-tbird", "athlon-4", "athlon-xp", "athlon-mp",
		"k8", "k8-sse3", "opteron", "opteron-sse3", "athlon64", "athlon64-sse3", "athlon-fx",
		"amdfam10", "barcelona",
		"bdver1", "bdver2", "bdver3", "bdver4",
		"btver1", "btver2",
		"znver1", "znver2", "znver3", "znver4", "znver5", "znver6",
		"x86-64", "x86-64-v2", "x86-64-v3", "x86-64-v4",
		"eden-x2", "nano", "nano-1000", "nano-2000", "nano-3000", "nano-x2", "eden-x4", "nano-x4",
		"lujiazui", "yongfeng", "shijidadao",
		"winchip-c6", "winchip2", "c3", "samuel-2", "c3-2", "nehemiah", "c7", "esther",
		"c86-4g-m4", "c86-4g-m6", "c86-4g-m7", "c86-4g-m8",
	)
}

func ActionParams() carapace.Action {
	return carapace.ActionValues(
		"align-loop-iterations",
		"align-threshold",
		"analyzer-bb-explosion-factor",
		"analyzer-max-constraints",
		"analyzer-max-enodes-for-full-dump",
		"analyzer-max-enodes-per-program-point",
		"analyzer-max-infeasible-edges",
		"analyzer-max-recursion-depth",
		"analyzer-max-svalue-depth",
		"analyzer-min-snodes-for-call-summary",
		"analyzer-text-art-ideal-canvas-width",
		"analyzer-text-art-string-ellipsis-head-len",
		"analyzer-text-art-string-ellipsis-tail-len",
		"analyzer-text-art-string-ellipsis-threshold",
		"asan-globals",
		"asan-instrument-allocas",
		"asan-instrument-reads",
		"asan-instrument-writes",
		"asan-instrumentation-with-call-threshold",
		"asan-kernel-mem-intrinsic-prefix",
		"asan-memintrin",
		"asan-stack",
		"asan-use-after-return",
		"auto-profile-bbs",
		"auto-profile-reorder-only",
		"avg-loop-niter",
		"avoid-fma-max-bits",
		"builtin-expect-probability",
		"builtin-string-cmp-inline-length",
		"case-values-threshold",
		"comdat-sharing-probability",
		"constructive-interference-size",
		"cxx-max-namespaces-for-diagnostic-help",
		"cycle-accurate-model",
		"destructive-interference-size",
		"dse-max-alias-queries-per-store",
		"dse-max-object-size",
		"early-inlining-insns",
		"file-cache-files",
		"file-cache-lines",
		"fsm-scale-path-stmts",
		"fully-pipelined-fma",
		"gcse-after-reload-critical-fraction",
		"gcse-after-reload-partial-fraction",
		"gcse-cost-distance-ratio",
		"gcse-unrestricted-cost",
		"ggc-min-expand",
		"ggc-min-heapsize",
		"gimple-fe-computed-hot-bb-threshold",
		"graphite-allow-codegen-errors",
		"graphite-max-arrays-per-scop",
		"graphite-max-nb-scop-params",
		"hardcfr-max-blocks",
		"hardcfr-max-inline-blocks",
		"hash-table-verification-limit",
		"hot-bb-count-fraction",
		"hot-bb-count-ws-permille",
		"hot-bb-frequency-fraction",
		"hwasan-instrument-allocas",
		"hwasan-instrument-mem-intrinsics",
		"hwasan-instrument-reads",
		"hwasan-instrument-stack",
		"hwasan-instrument-writes",
		"hwasan-random-frame-tag",
		"inline-heuristics-hint-percent",
		"inline-min-speedup",
		"inline-unit-growth",
		"integer-share-limit",
		"ipa-cp-eval-threshold",
		"ipa-cp-large-unit-insns",
		"ipa-cp-loop-hint-bonus",
		"ipa-cp-max-recursive-depth",
		"ipa-cp-min-recursive-probability",
		"ipa-cp-recursion-penalty",
		"ipa-cp-recursive-freq-factor",
		"ipa-cp-single-call-penalty",
		"ipa-cp-sweeps",
		"ipa-cp-unit-growth",
		"ipa-cp-value-list-size",
		"ipa-jump-function-lookups",
		"ipa-max-aa-steps",
		"ipa-max-agg-items",
		"ipa-max-loop-predicates",
		"ipa-max-param-expr-ops",
		"ipa-max-switch-predicate-bounds",
		"ipa-sra-deref-prob-threshold",
		"ipa-sra-max-replacements",
		"ipa-sra-ptr-growth-factor",
		"ipa-sra-ptrwrap-growth-factor",
		"ira-consider-dup-in-all-alts",
		"ira-loop-reserved-regs",
		"ira-max-conflict-table-size",
		"ira-max-loops-num",
		"ira-simple-lra-insn-threshold",
		"iv-always-prune-cand-set-bound",
		"iv-consider-all-candidates-bound",
		"iv-max-considered-uses",
		"ix86-vect-compare-costs",
		"ix86-vect-unroll-limit",
		"jump-table-max-growth-ratio-for-size",
		"jump-table-max-growth-ratio-for-speed",
		"l1-cache-line-size",
		"l1-cache-size",
		"l2-cache-size",
		"large-function-growth",
		"large-function-insns",
		"large-stack-frame",
		"large-stack-frame-growth",
		"large-unit-insns",
		"lazy-modules",
		"lim-expensive",
		"logical-op-non-short-circuit",
		"loop-block-tile-size",
		"loop-interchange-max-num-stmts",
		"loop-interchange-stride-ratio",
		"loop-invariant-max-bbs-in-loop",
		"loop-max-datarefs-for-datadeps",
		"loop-versioning-max-inner-insns",
		"loop-versioning-max-outer-insns",
		"lra-inheritance-ebb-probability-cutoff",
		"lra-max-considered-reload-pseudos",
		"lra-max-pseudos-points-log2-considered-for-preferences",
		"lto-max-locality-partition",
		"lto-max-partition",
		"lto-max-streaming-parallelism",
		"lto-min-partition",
		"lto-partition-locality-frequency-cutoff",
		"lto-partition-locality-size-cutoff",
		"lto-partitions",
		"max-average-unrolled-insns",
		"max-combine-insns",
		"max-combine-search-insns",
		"max-completely-peel-loop-nest-depth",
		"max-completely-peel-times",
		"max-completely-peeled-insns",
		"max-crossjump-edges",
		"max-cse-insns",
		"max-cse-path-length",
		"max-cselib-memory-locations",
		"max-debug-marker-count",
		"max-delay-slot-insn-search",
		"max-delay-slot-live-search",
		"max-devirt-targets",
		"max-dse-active-local-stores",
		"max-early-inliner-iterations",
		"max-fields-for-field-sensitive",
		"max-find-base-term-values",
		"max-fsm-thread-path-insns",
		"max-gcse-insertion-ratio",
		"max-gcse-memory",
		"max-goto-duplication-insns",
		"max-grow-copy-bb-insns",
		"max-hoist-depth",
		"max-inline-functions-called-once-insns",
		"max-inline-functions-called-once-loop-depth",
		"max-inline-insns-auto",
		"max-inline-insns-recursive",
		"max-inline-insns-recursive-auto",
		"max-inline-insns-single",
		"max-inline-insns-size",
		"max-inline-insns-small",
		"max-inline-recursive-depth",
		"max-inline-recursive-depth-auto",
		"max-isl-operations",
		"max-iterations-computation-cost",
		"max-iterations-to-track",
		"max-jump-thread-duplication-stmts",
		"max-jump-thread-paths",
		"max-last-value-rtl",
		"max-loop-header-insns",
		"max-modulo-backtrack-attempts",
		"max-partial-antic-length",
		"max-peel-branches",
		"max-peel-times",
		"max-peeled-insns",
		"max-pending-list-length",
		"max-pipeline-region-blocks",
		"max-pipeline-region-insns",
		"max-pow-sqrt-depth",
		"max-predicted-iterations",
		"max-reload-search-insns",
		"max-rtl-if-conversion-insns",
		"max-rtl-if-conversion-predictable-cost",
		"max-rtl-if-conversion-unpredictable-cost",
		"max-sched-extend-regions-iters",
		"max-sched-insn-conflict-delay",
		"max-sched-ready-insns",
		"max-sched-region-blocks",
		"max-sched-region-insns",
		"max-slsr-cand-scan",
		"max-speculative-devirt-maydefs",
		"max-ssa-name-query-depth",
		"max-store-chains-to-track",
		"max-stores-to-merge",
		"max-stores-to-sink",
		"max-stores-to-track",
		"max-tail-merge-comparisons",
		"max-tail-merge-iterations",
		"max-tracked-strlens",
		"max-tree-if-conversion-phi-args",
		"max-unroll-times",
		"max-unrolled-insns",
		"max-unswitch-depth",
		"max-unswitch-insns",
		"max-variable-expansions-in-unroller",
		"max-vartrack-expr-depth",
		"max-vartrack-reverse-op-size",
		"max-vartrack-size",
		"memtag-instrument-allocas",
		"memtag-instrument-mem-intrinsics",
		"min-crossjump-insns",
		"min-inline-recursive-probability",
		"min-insn-to-prefetch-ratio",
		"min-loop-cond-split-prob",
		"min-nondebug-insn-uid",
		"min-pagesize",
		"min-size-for-stack-sharing",
		"min-spec-prob",
		"min-vect-loop-bound",
		"modref-max-accesses",
		"modref-max-adjustments",
		"modref-max-bases",
		"modref-max-depth",
		"modref-max-escape-points",
		"modref-max-refs",
		"modref-max-tests",
		"openacc-kernels",
		"openacc-privatization",
		"parloops-chunk-size",
		"parloops-min-per-thread",
		"parloops-schedule",
		"partial-inlining-entry-probability",
		"phiopt-factor-max-stmts-live",
		"predictable-branch-outcome",
		"prefetch-dynamic-strides",
		"prefetch-latency",
		"prefetch-min-insn-to-mem-ratio",
		"prefetch-minimum-stride",
		"profile-func-internal-id",
		"ranger-debug",
		"ranger-logical-depth",
		"ranger-recompute-depth",
		"relation-block-limit",
		"rpo-vn-max-loop-depth",
		"sccvn-max-alias-queries-per-access",
		"scev-max-expr-complexity",
		"scev-max-expr-size",
		"sched-autopref-queue-depth",
		"sched-mem-true-dep-cost",
		"sched-pressure-algorithm",
		"sched-spec-prob-cutoff",
		"sched-state-edge-prob-cutoff",
		"selsched-insns-to-rename",
		"selsched-max-lookahead",
		"selsched-max-sched-times",
		"simultaneous-prefetches",
		"sink-frequency-threshold",
		"sms-dfa-history",
		"sms-loop-average-count-threshold",
		"sms-max-ii-factor",
		"sms-min-sc",
		"sra-max-propagations",
		"sra-max-scalarization-size-Osize",
		"sra-max-scalarization-size-Ospeed",
		"ssa-name-def-chain-limit",
		"ssp-buffer-size",
		"stack-clash-protection-guard-size",
		"stack-clash-protection-probe-interval",
		"store-forwarding-max-distance",
		"store-merging-allow-unaligned",
		"store-merging-max-size",
		"switch-conversion-max-branch-ratio",
		"threader-debug",
		"tm-max-aggregate-size",
		"tracer-dynamic-coverage",
		"tracer-dynamic-coverage-feedback",
		"tracer-max-code-growth",
		"tracer-min-branch-probability",
		"tracer-min-branch-probability-feedback",
		"tracer-min-branch-ratio",
		"transitive-relations-work-bound",
		"tree-reassoc-width",
		"tsan-distinguish-volatile",
		"tsan-instrument-func-entry-exit",
		"uninit-control-dep-attempts",
		"uninit-max-chain-len",
		"uninit-max-num-chains",
		"uninit-max-prune-work",
		"uninlined-function-insns",
		"uninlined-function-time",
		"uninlined-thunk-insns",
		"uninlined-thunk-time",
		"unlikely-bb-count-fraction",
		"unroll-jam-max-unroll",
		"unroll-jam-min-percent",
		"use-after-scope-direct-emission-threshold",
		"use-canonical-types",
		"vect-epilogues-nomask",
		"vect-induction-float",
		"vect-inner-loop-cost-factor",
		"vect-max-layout-candidates",
		"vect-max-peeling-for-alignment",
		"vect-max-version-for-alias-checks",
		"vect-max-version-for-alignment-checks",
		"vect-partial-vector-usage",
		"vect_allow_possibly_not_worthwhile_vectorizations",
		"vrp-block-limit",
		"vrp-cstload-limit",
		"vrp-sparse-threshold",
		"vrp-switch-limit",
		"vrp-vector-threshold",
		"x86-stlf-window-ninsns",
		"x86-stv-max-visits",
	)
}