package action

import "github.com/rsteube/carapace"

func ActionTargets() carapace.Action {
	return carapace.ActionValues(
        /// TODO some are not accepted
		"aot_android_asset_bundle",
		"aot_assembly_profile",
		"aot_assembly_release",
		"aot_elf_profile",
		"aot_elf_release",
		"compile_macos_framework",
		"copy_assets",
		"copy_flutter_bundle",
		"dart2js",
		"debug_android_application",
		"debug_bundle_windows_assets",
		"debug_bundle_windows_assets_uwp",
		"debug_ios_bundle_flutter_assets",
		"debug_macos_bundle_flutter_assets",
		"debug_macos_framework",
		"debug_universal_framework",
		"debug_unpack_ios",
		"debug_unpack_macos",
		"deferred_components_gen_snapshot_validator",
		"gen_dart_plugin_registrant",
		"gen_localizations",
		"kernel_snapshot",
		"linux_aot_bundle",
		"profile_android_application",
		"profile_bundle_windows_assets",
		"profile_bundle_windows_assets_uwp",
		"profile_ios_bundle_flutter_assets",
		"profile_macos_bundle_flutter_assets",
		"profile_unpack_ios",
		"profile_unpack_macos",
		"release_android_application",
		"release_bundle_windows_assets",
		"release_bundle_windows_assets_uwp",
		"release_flutter_bundle",
		"release_ios_bundle_flutter_assets",
		"release_macos_bundle_flutter_assets",
		"release_unpack_ios",
		"release_unpack_macos",
		"unpack_linux",
		"unpack_windows",
		"unpack_windows_uwp",
		"web_entrypoint",
		"web_release_bundle",
		"web_service_worker",
		"windows_aot_bundle",
		"windows_uwp_aot_bundle",
		"windows_uwp_aot_bundle",

		// TODO
		//"release_bundle_${getNameForTargetPlatform(targetPlatform)}_assets",
		//"profile_bundle_${getNameForTargetPlatform(targetPlatform)}_assets",
		//"debug_bundle_${getNameForTargetPlatform(targetPlatform)}_assets",
		//"android_aot_${getNameForBuildMode(buildMode)}_",
		//"android_aot_bundle_${getNameForBuildMode(dependency.buildMode)}_",
		//"android_aot_deferred_components_bundle_${getNameForBuildMode(dependency.buildMode)}_",
	)
}
