# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: puttyconfig
description: Add PuTTY saved session configuration for specified hostname to Windows registry
hidden: true
flags:
    --leaf=: Add a configuration for connecting to a leaf cluster
    -p, --port=: SSH port on a remote host
