package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"

	"github.com/carapace-sh/carapace-bin/pkg/strblob"
)

const blobImportPath = "github.com/carapace-sh/carapace-bin/pkg/strblob"

// generateBlobFile renders the generated accessor file for a package.
func generateBlobFile(pkg, varName string, blob []byte) ([]byte, error) {
	src := fmt.Sprintf(`// Code generated by cmd/strcompress; DO NOT EDIT.

package %s

import %q

var %s = strblob.Blob(%s)
`, pkg, blobImportPath, varName, strconv.Quote(string(blob)))
	return format.Source([]byte(src))
}

// readExistingBlob recovers the strings of a previously generated blob so
// that re-running the tool keeps old offsets stable.
func readExistingBlob(dir string) (vals []string, varName string, err error) {
	path := filepath.Join(dir, blobFileName)
	src, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, "", nil
	} else if err != nil {
		return nil, "", err
	}

	file, err := parser.ParseFile(token.NewFileSet(), path, src, parser.SkipObjectResolution)
	if err != nil {
		return nil, "", fmt.Errorf("%s: %w", path, err)
	}

	var data string
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}
		for _, spec := range gen.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok || len(valueSpec.Names) != 1 || len(valueSpec.Values) != 1 {
				continue
			}
			call, ok := valueSpec.Values[0].(*ast.CallExpr)
			if !ok || len(call.Args) != 1 {
				continue
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				continue
			}
			if ident, ok := sel.X.(*ast.Ident); !ok || ident.Name != "strblob" || sel.Sel.Name != "Blob" {
				continue
			}
			lit, ok := call.Args[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				continue
			}
			data, err = strconv.Unquote(lit.Value)
			if err != nil {
				return nil, "", fmt.Errorf("%s: %w", path, err)
			}
			varName = valueSpec.Names[0].Name
		}
	}
	if varName == "" {
		return nil, "", fmt.Errorf("%s: no strblob.Blob declaration found", path)
	}

	vals, err = strblob.Decode(data)
	if err != nil {
		return nil, "", fmt.Errorf("%s: %w", path, err)
	}
	return vals, varName, nil
}
