package android

import (
	"github.com/carapace-sh/carapace"
)

// ActionIntentActions completes intent actions
//
//	android.intent.action.MAIN (Activity Action: Start as a main entry point, does not expect to receive data)
//	android.intent.action.VIEW (Activity Action: Display the data to the user.)
//	android.intent.action.EDIT (Activity Action: Provide explicit editable access to the given data)
func ActionIntentActions() carapace.Action {
	return carapace.ActionValuesDescribed(
		"android.intent.action.MAIN", "Activity Action: Start as a main entry point, does not expect to receive data",
		"android.intent.action.VIEW", "Activity Action: Display the data to the user.",
		"android.intent.action.QUICK_VIEW", "Activity Action: Quick view the data.",
		"android.intent.action.ATTACH_DATA", "Used to indicate that some piece of data should be attached to some other place.",
		"android.intent.action.EDIT", "Activity Action: Provide explicit editable access to the given data",
		"android.intent.action.INSERT_OR_EDIT", "Activity Action: Pick an existing item, or insert a new item, and then edit it",
		"android.intent.action.PICK", "Activity Action: Pick an item from the data, returning what was selected",
		"android.intent.action.CREATE_REMINDER", "Activity Action: Creates a reminder",
		"android.intent.action.CREATE_SHORTCUT", "Activity Action: Creates a shortcut",
		"android.intent.action.CHOOSER", "Activity Action: Display an activity chooser, allowing the user to pick what they want to before proceeding.",
		"android.intent.action.GET_CONTENT", "Activity Action: Allow the user to select a particular kind of data and return it.",
		"android.intent.action.DIAL", "Activity Action: Dial a number as specified by the data.",
		"android.intent.action.CALL", "Activity Action: Perform a call to someone specified by the data",
		"android.intent.action.CALL_EMERGENCY", "Activity Action: Perform a call to an emergency number specified by the data",
		"android.intent.action.DIAL_EMERGENCY", "Activity Action: Dial a emergency number specified by the data.",
		"android.intent.action.CALL_PRIVILEGED", "Activity action: Perform a call to any number (emergency or not) specified by the data",
		"android.intent.action.CARRIER_SETUP", "Activity Action: Main entry point for carrier setup apps",
		"android.intent.action.SENDTO", "Activity Action: Send a message to someone specified by the data",
		"android.intent.action.SEND", "Activity Action: Deliver some data to someone else.",
		"android.intent.action.SEND_MULTIPLE", "Activity Action: Deliver multiple data to someone else",
		"android.intent.action.ANSWER", "Activity Action: Handle an incoming phone call",
		"android.intent.action.INSERT", "Activity Action: Insert an empty item into the given container",
		"android.intent.action.PASTE", "Activity Action: Create a new item in the given container, initializing it from the current contents of the clipboard",
		"android.intent.action.DELETE", "Activity Action: Delete the given data from its container",
		"android.intent.action.RUN", "Activity Action: Run the data, whatever that means",
		"android.intent.action.SYNC", "Activity Action: Perform a data synchronization",
		"android.intent.action.PICK_ACTIVITY", "Activity Action: Pick an activity given an intent, returning the class selected",
		"android.intent.action.SEARCH", "Activity Action: Perform a search",
		"android.intent.action.SYSTEM_TUTORIAL", "Activity Action: Start the platform-defined tutorial",
		"android.intent.action.WEB_SEARCH", "Activity Action: Perform a web search",
		"android.intent.action.ASSIST", "Activity Action: Perform assist action",
		"android.intent.action.VOICE_ASSIST", "Activity Action: Perform voice assist action",
		"android.intent.action.ALL_APPS", "Activity Action: List all available applications",
		"android.intent.action.SET_WALLPAPER", "Activity Action: Show settings for choosing wallpaper",
		"android.intent.action.BUG_REPORT", "Activity Action: Show activity for reporting a bug",
		"android.intent.action.FACTORY_TEST", "Activity Action: Main entry point for factory tests.",
		"android.intent.action.CALL_BUTTON", "Activity Action: The user pressed the \"call\" button to go to the dialer or other appropriate UI for placing a call",
		"android.intent.action.VOICE_COMMAND", "Activity Action: Start Voice Command",
		"android.intent.action.SEARCH_LONG_PRESS", "Activity Action: Start action associated with long pressing on the search key",
		"android.intent.action.APP_ERROR", "Activity Action: The user pressed the \"Report\" button in the crash/ANR dialog.",
		"android.intent.action.POWER_USAGE_SUMMARY", "Activity Action: Show power usage information to the user",
		"android.intent.action.UPGRADE_SETUP", "Activity Action: Setup wizard to launch after a platform update.",
		"android.intent.action.INSTALL_PACKAGE", "Activity Action: Launch application installer",
		"android.intent.action.INSTALL_FAILURE", "Activity Action: Activity to handle split installation failures",
		"android.intent.action.UNINSTALL_PACKAGE", "Activity Action: Launch application uninstaller",
		"android.intent.action.SCREEN_OFF", "Broadcast Action: Sent when the device goes to sleep and becomes non-interactive",
		"android.intent.action.SCREEN_ON", "Broadcast Action: Sent when the device wakes up and becomes interactive",
		"android.intent.action.DREAMING_STOPPED", "Broadcast Action: Sent after the system stops dreaming",
		"android.intent.action.DREAMING_STARTED", "Broadcast Action: Sent after the system starts dreaming",
		"android.intent.action.USER_PRESENT", "Broadcast Action: Sent when the user is present after device wakes up (e.g when the keyguard is gone)",
		"android.intent.action.TIME_TICK", "Broadcast Action: The current time has changed.",
		"android.intent.action.TIME_SET", "Broadcast Action: The time was set",
		"android.intent.action.DATE_CHANGED", "Broadcast Action: The date has changed",
		"android.intent.action.TIMEZONE_CHANGED", "Broadcast Action: The timezone has changed.",
		"android.intent.action.ALARM_CHANGED", "Alarm Changed Action: This is broadcast when the AlarmClock application's alarm is set or unset.",
		"android.intent.action.LOCKED_BOOT_COMPLETED", "Broadcast Action: This is broadcast once, after the user has finished booting, but while still in the \"locked\" state.",
		"android.intent.action.BOOT_COMPLETED", "Broadcast Action: This is broadcast once, after the user has finished booting.",
		"android.intent.action.CLOSE_SYSTEM_DIALOGS", "Broadcast Action: This is broadcast when a user action should request a temporary system dialog to dismiss.",
		"android.intent.action.PACKAGE_INSTALL", "Broadcast Action: Trigger the download and eventual installation of a package",
		"android.intent.action.PACKAGE_ADDED", "Broadcast Action: A new application package has been installed on the device.",
		"android.intent.action.PACKAGE_REPLACED", "Broadcast Action: A new version of an application package has been installed, replacing an existing version that was previously installed.",
		"android.intent.action.MY_PACKAGE_REPLACED", "Broadcast Action: A new version of your application has been installed over an existing one.",
		"android.intent.action.PACKAGE_REMOVED", "Broadcast Action: An existing application package has been removed from the device.",
		"android.intent.action.PACKAGE_CHANGED", "Broadcast Action: An existing application package has been changed (for example, a component has been enabled or disabled).",
		"android.intent.action.PACKAGE_UNSTOPPED", "Broadcast Action: An application package that was previously in the stopped state has been started and is no longer considered stopped",
		"android.intent.action.QUERY_PACKAGE_RESTART", "",
		"android.intent.action.PACKAGE_RESTARTED", "Broadcast Action: The user has restarted a package, and all of its processes have been killed.",
		"android.intent.action.PACKAGE_DATA_CLEARED", "Broadcast Action: The user has cleared the data of a package.",
		"android.intent.action.PACKAGES_SUSPENDED", "Broadcast Action: Packages have been suspended",
		"android.intent.action.PACKAGES_UNSUSPENDED", "Broadcast Action: Packages have been unsuspended",
		"android.intent.action.MY_PACKAGE_SUSPENDED", "Broadcast Action: Sent to a package that has been suspended by the system.",
		"android.intent.action.MY_PACKAGE_UNSUSPENDED", "Broadcast Action: Sent to a package that has been unsuspended",
		"android.intent.action.UID_REMOVED", "Broadcast Action: A uid has been removed from the system.",
		"android.intent.action.PACKAGE_FIRST_LAUNCH", "Broadcast Action: Sent to the installer package of an application when that application is first launched (that is the first time it is moved out of the stopped state).",
		"android.intent.action.PACKAGE_NEEDS_VERIFICATION", "Broadcast Action: Sent to the system package verifier when a package needs to be verified.",
		"android.intent.action.PACKAGE_VERIFIED", "Broadcast Action: Sent to the system package verifier when a package is verified.",
		"android.intent.action.WALLPAPER_CHANGED", "Broadcast Action: The current system wallpaper has changed.",
		"android.intent.action.CONFIGURATION_CHANGED", "Broadcast Action: The current device",
		"android.intent.action.LOCALE_CHANGED", "Broadcast Action: The receiver's effective locale has changed",
		"android.intent.action.BATTERY_CHANGED", "Broadcast Action: This is a sticky broadcast containing the charging state, level, and other information about the battery.",
		"android.intent.action.BATTERY_LOW", "Broadcast Action: Indicates low battery condition on the device.",
		"android.intent.action.BATTERY_OKAY", "Broadcast Action: Indicates the battery is now okay after being low.",
		"android.intent.action.ACTION_POWER_CONNECTED", "Broadcast Action: External power has been connected to the device.",
		"android.intent.action.ACTION_SHUTDOWN", "Broadcast Action: Device is shutting down.",
		"android.intent.action.DEVICE_STORAGE_LOW", "Broadcast Action: A sticky broadcast that indicates low storage space condition on the device",
		"android.intent.action.DEVICE_STORAGE_OK", "Broadcast Action: Indicates low storage space condition on the device no longer exists",
		"android.intent.action.DEVICE_STORAGE_FULL", "Broadcast Action: A sticky broadcast that indicates a storage space full condition on the device.",
		"android.intent.action.DEVICE_STORAGE_NOT_FULL", "Broadcast Action: Indicates storage space full condition on the device no longer exists",
		"android.intent.action.MANAGE_PACKAGE_STORAGE", "Broadcast Action: Indicates low memory condition notification acknowledged by user and package management should be started.",
		"android.intent.action.UMS_CONNECTED", "Broadcast Action: The device has entered USB Mass Storage mode.",
		"android.intent.action.UMS_DISCONNECTED", "Broadcast Action: The device has exited USB Mass Storage mode.",
		"android.intent.action.MEDIA_REMOVED", "Broadcast Action: External media has been removed.",
		"android.intent.action.MEDIA_UNMOUNTED", "Broadcast Action: External media is present, but not mounted at its mount point.",
		"android.intent.action.MEDIA_CHECKING", "Broadcast Action: External media is present, and being disk-checked The path to the mount point for the checking media is contained in the Intent.mData field",
		"android.intent.action.MEDIA_NOFS", "Broadcast Action: External media is present, but is using an incompatible fs (or is blank) The path to the mount point for the checking media is contained in the Intent.mData field",
		"android.intent.action.MEDIA_MOUNTED", "Broadcast Action: External media is present and mounted at its mount point.",
		"android.intent.action.MEDIA_SHARED", "Broadcast Action: External media is unmounted because it is being shared via USB mass storage.",
		"android.intent.action.MEDIA_UNSHARED", "Broadcast Action: External media is no longer being shared via USB mass storage.",
		"android.intent.action.MEDIA_BAD_REMOVAL", "Broadcast Action: External media was removed from SD card slot, but mount point was not unmounted.",
		"android.intent.action.MEDIA_UNMOUNTABLE", "Broadcast Action: External media is present but cannot be mounted.",
		"android.intent.action.MEDIA_EJECT", "Broadcast Action: User has expressed the desire to remove the external storage media.",
		"android.intent.action.MEDIA_SCANNER_STARTED", "Broadcast Action: The media scanner has started scanning a directory.",
		"android.intent.action.MEDIA_SCANNER_FINISHED", "Broadcast Action: The media scanner has finished scanning a directory.",
		"android.intent.action.MEDIA_SCANNER_SCAN_FILE", "Broadcast Action: Request the media scanner to scan a file and add it to the media database",
		"android.intent.action.MEDIA_BUTTON", "Broadcast Action: The \"Media Button\" was pressed.",
		"android.intent.action.CAMERA_BUTTON", "Broadcast Action: The \"Camera Button\" was pressed.",
		"android.intent.action.AIRPLANE_MODE", "",
		"android.intent.action.USER_UNLOCKED", "Broadcast Action: Sent when the credential-encrypted private storage has become unlocked for the target user.",
		"android.intent.action.GLOBAL_BUTTON", "Broadcast Action: A global button was pressed.",
		"android.intent.action.OVERLAY_CHANGED", "Broadcast Action: An overlay package has changed.",
		"android.intent.action.OPEN_DOCUMENT", "Activity Action: Allow the user to select and return one or more existing documents.",
		"android.intent.action.CREATE_DOCUMENT", "Activity Action: Allow the user to create a new document.",
		"android.intent.action.TRANSLATE", "Activity Action: Perform text translation",
		"android.intent.action.DEFINE", "Activity Action: Define the meaning of the selected word(s)",
		"android.intent.action.MASTER_CLEAR", "Deprecated - use ACTION_FACTORY_RESET instead",
		"android.intent.action.FACTORY_RESET", "A broadcast action to trigger a factory reset",
		"android.os.action.SETTING_RESTORED", "Broadcast action: report that a settings element is being restored from backup.",
		"android.intent.action.PROCESS_TEXT", "Activity Action: Process a piece of text",
		"android.intent.action.SIM_STATE_CHANGED", "Broadcast Action: The sim card state has changed.",
		"android.intent.action.SERVICE_STATE", "Broadcast Action: indicate that the phone service state has changed.",
		"android.intent.action.LOAD_DATA", "Used by",
		"android.intent.action.THERMAL_EVENT", "Broadcast action: reports when a new thermal event has been reached.",
		"android.intent.action.DOCK_IDLE", "Broadcast Action: Indicates the dock in idle state while device is docked",
		"android.intent.action.DOCK_ACTIVE", "Broadcast Action: Indicates the dock in active state while device is docked",
		"android.intent.action.VIEW_LOCUS", "Activity Action: Display an activity state associated with an unique",
		"android.intent.action.CREATE_NOTE", "Activity Action: Starts a note-taking activity that can be used to create a note.",
		"android.intent.action.UNARCHIVE_PACKAGE", "Broadcast Action: Sent to the responsible installer of an archived package when unarchival is requested",
	)
}
