version: 2.1
workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - doc:
          filters:
            branches:
              only: /master/
            tags:
              ignore: /.*/
  tags:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

commands:
  run_tests:
    steps:
      - run:
          name: "build"
          command: |
            go generate ./...
            go get -t -v ./...
            PATH=$PATH:$PWD/bin go test -v ./...
            cd cmd/carapace
            go build
            go vet

jobs:
  build:
    docker:
      - image: circleci/golang:latest
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run_tests
      - run:
          name: "Check formatting"
          command: diff -u <(echo -n) <(gofmt -d -s .)
      - run:
          name: "staticcheck"
          command: go install honnef.co/go/tools/cmd/staticcheck@2021.1.1 && staticcheck ./...
      - run:
          name: "caralint"
          command: go run ./cmd/caralint completers/*/cmd/*.go
  doc:
    docker:
      - image: ghcr.io/rsteube/carapace
    steps:
      - checkout
      - run:
          name: "build docs"
          command: |
            sed -i 's/\[output.linkcheck\]/#[output.linkcheck]/' docs/book.toml
            sh .circleci/completers.sh > docs/src/completers.md
            mdbook build docs
            sh .circleci/badge.sh > docs/book/badge.svg
      - run:
          name: "push gh-pages"
          command: |
            cd docs/book/
            git init
            git config user.name rsteube
            git config user.email rsteube@users.noreply.github.com
            git add .
            git commit -m "initial commit [ci skip]"
            git push --force https://rsteube:${GITHUB_TOKEN}@github.com/rsteube/carapace-bin.git master:gh-pages
  release:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout  
      - run: AUR_KEY=$(echo $AUR_KEY | base64 -d) && cd cmd/carapace && go generate ./... && curl -sL https://git.io/goreleaser | bash
