# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: login [flags]
description: Login to one instance
flags:
    --help: Show help message and exit
    -h, --host=: Host to access
    -s, --scenario-name=: Name of the scenario to target
