# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create [flags]
description: Use the provisioner to start the instances
flags:
    --help: Show help message and exit
    -d, --driver-name=: Name of the driver to use
    -s, --scenario-name=: Name of the scenario to target
