# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rollback
description: roll back a release to a previous revision
group: main
flags:
    --cleanup-on-fail: allow deletion of new resources created in this rollback when rollback fails
    --dry-run: simulate a rollback
    --force: force resource update through delete/recreate if needed
    --history-max=: limit the maximum number of revisions saved per release. Use 0 for no limit
    --no-hooks: prevent hooks from running during rollback
    --recreate-pods: performs pods restart for the resource if applicable
    --timeout=: time to wait for any individual Kubernetes operation (like Jobs for hooks)
    --wait: if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as --timeout
    --wait-for-jobs: if set and --wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as --timeout
