name: Completer
description: Request a new Completer
title: "completer: <title>"
labels: [enhancement, completer, polar]
body:
- type: input
  attributes:
    label: Name
    description: Name of the command (as typed on the command line).
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Short description of the command (just a sentence about what it is or does).
  validations:
    required: true
- type: input
  attributes:
    label: Homepage
    description: Homepage of the command (or repository if there is none).
  validations:
    required: true
- type: input
  attributes:
    label: Documentation
    description: Documentation of the command (if available).
  validations:
    required: false
- type: input
  attributes:
    label: Repository
    description: Repository of the command (if available).
  validations:
    required: false
- type: checkboxes
  attributes:
    label: OS
    description: Operating System the command supports.
    options:
    - label: Linux
    - label: OSX
    - label: Termux
    - label: Windows
- type: dropdown
  attributes:
    label: Complexity
    description: Complexity of the command.
    options:
    - S (no subcommands, low argument complexity)
    - M (less than 20 subcommands, medium argument complexity)
    - L (over 20 subcommands, large argument complexity)
    - Bottomless Pit (git, aws, gcloud, az, kubectl)
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the request!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
