package cmd

import (
	"github.com/carapace-sh/carapace"
	"github.com/spf13/cobra"
)

var modCmd = &cobra.Command{
	Use:   "mod",
	Short: "Queries the Bzlmod external dependency graph",
	Run:   func(cmd *cobra.Command, args []string) {},
}

func init() {
	carapace.Gen(modCmd).Standalone()

	modCmd.Flags().StringSlice("action_env", nil, "Specifies the set of environment variables available to actions with target")
	modCmd.Flags().Bool("all_repos", false, "For `mod show_repo`: display all repos in the entire workspace.")
	modCmd.Flags().Bool("all_visible_repos", false, "For `mod show_repo`: display all repos visible to the chosen base module, under their apparent names.")
	modCmd.Flags().Bool("allow_analysis_failures", false, "If true, an analysis failure of a rule target results in the target's propagation")
	modCmd.Flags().Bool("allow_unresolved_symlinks", false, "If enabled, Bazel allows the use of `ctx.action.declare_symlink()` and the use of")
	modCmd.Flags().String("allowed_cpu_values", "", "Allowed values for the `--cpu` flag.")
	modCmd.Flags().String("analysis_testing_deps_limit", "", "Sets the maximum number of transitive dependencies through a rule attribute with")
	modCmd.Flags().String("archived_tree_artifact_mnemonics_filter", "", "Regex filter for mnemonics of actions for which we should create archived tree artifacts. This option is a no-op for actions which do not generate tree artifacts.")
	modCmd.Flags().String("base_module", "", "Specify a module relative to which the specified target repos will be interpreted.")
	modCmd.Flags().Bool("build_runfile_links", false, "If true, build runfiles symlink forests for all targets.  If false, write them only when required by a local action, test or run command.")
	modCmd.Flags().Bool("build_runfile_manifests", false, "If true, write runfiles manifests for all targets. If false, omit them. Local tests will fail to run when false.")
	modCmd.Flags().String("charset", "", "Chooses the character set to use for the tree. Only affects text output. Valid values")
	modCmd.Flags().Bool("check_licenses", false, "Deprecated in favor of `--config=check_licenses`.")
	modCmd.Flags().Bool("check_visibility", false, "If disabled, visibility errors in target dependencies are demoted to warnings.")
	modCmd.Flags().Bool("collect_code_coverage", false, "If specified, Bazel will instrument code (using offline instrumentation where")
	modCmd.Flags().StringP("compilation_mode", "c", "", "Specify the mode the binary will be built in. Values: `fastbuild`, `dbg`, `opt`.")
	modCmd.Flags().String("cpu", "", "Deprecated: this flag is not used internally by Blaze although there are legacy platform")
	modCmd.Flags().Bool("cycles", false, "Points out dependency cycles inside the displayed tree.")
	modCmd.Flags().String("default_visibility", "", "Default visibility for packages that don't set it explicitly ('public' or 'private').")
	modCmd.Flags().StringSlice("define", nil, "Each `--define` option specifies an assignment for a build variable.")
	modCmd.Flags().StringSlice("deleted_packages", nil, "A comma-separated list of names of packages which the build system will consider non-existent, even if they are visible somewhere on the package path.")
	modCmd.Flags().String("depth", "", "Maximum display depth of the dependency tree. A depth of 1 displays the direct")
	modCmd.Flags().String("enable_runfiles", "", "Enable runfiles symlink tree; By default, it's off on Windows, on on other platforms.")
	modCmd.Flags().Bool("enforce_constraints", false, "Checks the environments each target is compatible with and reports errors if any target has dependencies that don't support the same environments")
	modCmd.Flags().StringSlice("exec_aspects", nil, "Comma-separated list of aspects to be applied to exec-configured targets, regardless of whether or not they are top-level targets. This is an experimental feature and is subject to change.")
	modCmd.Flags().StringSlice("experimental_action_listener", nil, "Deprecated in favor of aspects. Use `action_listener` to attach an `extra_action` to")
	modCmd.Flags().Bool("experimental_allow_map_directory", false, "If enabled, Bazel allows the use of ctx.actions.map_directory(). This allows for the creation of actions based on the files in a directory through a user defined Starlark function and a <code>template_ctx</code> that supports basic action generation APIs.")
	modCmd.Flags().Bool("experimental_check_external_other_files", false, "Check for modifications made to the non-output, non-repo external files, e.g. host files.")
	modCmd.Flags().Bool("experimental_check_output_files", false, "Check for modifications made to the output files of a build. Consider setting this flag to false if you don't expect these files to change outside of bazel since it will speed up subsequent runs as they won't have to check a previous run's cache.")
	modCmd.Flags().Bool("experimental_collect_code_coverage_for_generated_files", false, "If specified, Bazel will also generate collect coverage information for generated files.")
	modCmd.Flags().Bool("experimental_debug_selects_always_succeed", false, "When set, `select` functions with no matching clause will return an empty value, instead")
	modCmd.Flags().Bool("experimental_enforce_transitive_visibility", false, "If true, enable package()s to set the transitive_visibility attribute to restrict which packages may depend on them.")
	modCmd.Flags().Bool("experimental_exclude_defines_from_exec_config", false, "If true, don't propagate `--define`s to the exec transition at default; only propagate")
	modCmd.Flags().String("experimental_exec_config", "", "If set to `//some:label:my.bzl%my_transition`, uses my_transition for `cfg = \"exec\"`")
	modCmd.Flags().String("experimental_exec_configuration_distinguisher", "", "Please only use this flag as part of a suggested migration or testing strategy due to")
	modCmd.Flags().Bool("experimental_extended_sanity_checks", false, "Enables internal validation checks to make sure that configured target implementations only access things they should. Causes a performance hit.")
	modCmd.Flags().String("experimental_lazy_macro_expansion_packages", "", "List of packages in which symbolic macro are expanded only if necessary.")
	modCmd.Flags().String("experimental_max_directories_to_eagerly_visit_in_globbing", "", "If non-negative, the first time a glob is evaluated in a package, the subdirectories of the package will be traversed in order to warm filesystem caches and compensate for lack of parallelism in globbing. At most this many directories will be visited.")
	modCmd.Flags().String("experimental_output_directory_naming_scheme", "", "Please only use this flag as part of a suggested migration or testing strategy. In")
	modCmd.Flags().String("experimental_output_paths", "", "Which model to use for where in the output tree rules write their outputs, particularly")
	modCmd.Flags().StringSlice("experimental_override_platform_cpu_name", nil, "Each entry should be of the form `label=value` where label refers to a platform and values")
	modCmd.Flags().String("experimental_platform_in_output_dir", "", "If true, a shortname for the target platform is used in the output directory name")
	modCmd.Flags().StringSlice("experimental_propagate_custom_flag", nil, "Which custom flags (starlark flags or defines) to propagate to the exec transition, by")
	modCmd.Flags().Bool("experimental_remotable_source_manifests", false, "Whether to make source manifest actions remotable")
	modCmd.Flags().Bool("experimental_strict_fileset_output", false, "If this option is enabled, filesets will treat all output artifacts as regular files. They will not traverse directories or be sensitive to symlinks.")
	modCmd.Flags().Bool("experimental_throttle_action_cache_check", false, "Whether to throttle the check whether an action is cached.")
	modCmd.Flags().Bool("experimental_use_platforms_in_output_dir_legacy_heuristic", false, "Please only use this flag as part of a suggested migration or testing strategy. Note")
	modCmd.Flags().Bool("experimental_writable_outputs", false, "If true, the file permissions of action outputs are set to `0755` instead of `0555`")
	modCmd.Flags().String("extension_filter", "", "Only display the usages of these module extensions and the repos generated by them if their respective flags are set. If set, the result graph will only include paths that contain modules using the specified extensions. An empty list disables the filter, effectively specifying all possible extensions.")
	modCmd.Flags().String("extension_info", "", "Specify how much detail about extension usages to include in the query result.")
	modCmd.Flags().String("extension_usages", "", "Specify modules whose extension usages will be displayed in the show_extension query.")
	modCmd.Flags().StringSlice("features", nil, "The given features will be enabled or disabled by default for targets built in the target configuration.")
	modCmd.Flags().Bool("fetch", false, "Allows the command to fetch external dependencies. If set to false, the command will utilize any cached version of the dependency, and if none exists, the command will result in failure.")
	modCmd.Flags().StringSlice("flag_alias", nil, "Sets a shorthand name for a Starlark flag. It takes a single key-value pair in the form")
	modCmd.Flags().String("from", "", "The module(s) starting from which the dependency graph query will be displayed. Check")
	modCmd.Flags().StringSlice("host_action_env", nil, "Specifies the set of environment variables available to actions with execution")
	modCmd.Flags().String("host_compilation_mode", "", "Specify the mode the tools used during the build will be built in. Values:")
	modCmd.Flags().String("host_cpu", "", "The host CPU.")
	modCmd.Flags().StringSlice("host_features", nil, "The given features will be enabled or disabled by default for targets built in the exec configuration.")
	modCmd.Flags().Bool("include_builtin", false, "Include built-in modules in the dependency graph. Disabled by default because it is quite noisy.")
	modCmd.Flags().String("include_config_fragments_provider", "", "INTERNAL BLAZE DEVELOPER FEATURE: If `direct`, all configured targets expose")
	modCmd.Flags().Bool("include_unused", false, "The queries will also take into account and display the unused modules, which are not")
	modCmd.Flags().Bool("incompatible_always_include_files_in_data", false, "If true, native rules add `DefaultInfo.files` of data dependencies to their runfiles,")
	modCmd.Flags().Bool("incompatible_auto_exec_groups", false, "When enabled, an exec groups is automatically created for each toolchain used by a rule.")
	modCmd.Flags().Bool("incompatible_bazel_test_exec_run_under", false, "If enabled, `bazel test --run_under=//:runner` builds `//:runner` in the exec")
	modCmd.Flags().Bool("incompatible_bep_cpu_from_platform", false, "If specified, the value of the cpu constraint (@platforms//cpu:cpu) of the target platform is used to set the Configuration.cpu and Configuration.platform_name fields in the BEP.")
	modCmd.Flags().Bool("incompatible_check_testonly_for_output_files", false, "If enabled, check testonly for prerequisite targets that are output files by looking up the testonly of the generating rule. This matches visibility checking.")
	modCmd.Flags().Bool("incompatible_compact_repo_mapping_manifest", false, "If enabled, the `{binary}.repo_mapping` file emits a module extension's repo mapping")
	modCmd.Flags().Bool("incompatible_config_setting_private_default_visibility", false, "If incompatible_enforce_config_setting_visibility=false, this is a noop. Else, if this flag is false, any config_setting without an explicit visibility attribute is //visibility:public. If this flag is true, config_setting follows the same visibility logic as all other rules. See https://github.com/bazelbuild/bazel/issues/12933.")
	modCmd.Flags().String("incompatible_disable_select_on", "", "List of flags for which the use in `select()` is disabled.")
	modCmd.Flags().Bool("incompatible_enforce_config_setting_visibility", false, "If true, enforce config_setting visibility restrictions. If false, every config_setting is visible to every target. See https://github.com/bazelbuild/bazel/issues/12932.")
	modCmd.Flags().Bool("incompatible_exclude_starlark_flags_from_exec_config", false, "If true, don't propagate starlark flags to the exec transition at default; only propagate starlark flags specified in `--experimental_propagate_custom_flag`.")
	modCmd.Flags().Bool("incompatible_filegroup_runfiles_for_data", false, "If true, runfiles of targets listed in the srcs attribute are available to targets that consume the filegroup as a data dependency.")
	modCmd.Flags().String("incompatible_limit_platforms_in_output_dir_to", "", "Added for gradual rollout of --experimental_platform_in_output_dir to non-exec configurations. Takes a comma-separated list of platform labels. If set, --experimental_platform_in_output_dir is only enabled for platforms in this list. Otherwise, --experimental_platform_in_output_dir applies to all platforms.")
	modCmd.Flags().Bool("incompatible_merge_genfiles_directory", false, "If true, the genfiles directory is folded into the bin directory.")
	modCmd.Flags().Bool("incompatible_modify_execution_info_additive", false, "When enabled, passing multiple `--modify_execution_info` flags is additive.")
	modCmd.Flags().Bool("incompatible_target_cpu_from_platform", false, "If specified, the value of the cpu constraint (`@platforms//cpu:cpu`) of")
	modCmd.Flags().Bool("instrument_test_targets", false, "When coverage is enabled, specifies whether to consider instrumenting test rules.")
	modCmd.Flags().String("instrumentation_filter", "", "When coverage is enabled, only rules with names included by the")
	modCmd.Flags().String("legacy_globbing_threads", "", "Number of threads to use for glob evaluation. Takes an integer, or a keyword (\"auto\", \"HOST_CPUS\", \"HOST_RAM\"), optionally followed by an operation ([-|*]<float>) eg. \"auto\", \"HOST_CPUS*.5\". \"auto\" means to use a reasonable value derived from the machine's hardware profile (e.g. the number of processors).")
	modCmd.Flags().String("loading_phase_threads", "", "Number of parallel threads to use for the loading/analysis phase.Takes an integer, or a keyword (\"auto\", \"HOST_CPUS\", \"HOST_RAM\"), optionally followed by an operation ([-|*]<float>) eg. \"auto\", \"HOST_CPUS*.5\". \"auto\" sets a reasonable default based on host resources. Must be at least 1.")
	modCmd.Flags().String("min_param_file_size", "", "Minimum command line length before creating a parameter file.")
	modCmd.Flags().StringSlice("modify_execution_info", nil, "Add or remove keys from an action's execution info based on action mnemonic.")
	modCmd.Flags().Bool("noall_repos", false, "For `mod show_repo`: display all repos in the entire workspace.")
	modCmd.Flags().Bool("noall_visible_repos", false, "For `mod show_repo`: display all repos visible to the chosen base module, under their apparent names.")
	modCmd.Flags().Bool("noallow_analysis_failures", false, "If true, an analysis failure of a rule target results in the target's propagation")
	modCmd.Flags().Bool("noallow_unresolved_symlinks", false, "If enabled, Bazel allows the use of `ctx.action.declare_symlink()` and the use of")
	modCmd.Flags().Bool("nobuild_runfile_links", false, "If true, build runfiles symlink forests for all targets.  If false, write them only when required by a local action, test or run command.")
	modCmd.Flags().Bool("nobuild_runfile_manifests", false, "If true, write runfiles manifests for all targets. If false, omit them. Local tests will fail to run when false.")
	modCmd.Flags().Bool("nocheck_licenses", false, "Deprecated in favor of `--config=check_licenses`.")
	modCmd.Flags().Bool("nocheck_visibility", false, "If disabled, visibility errors in target dependencies are demoted to warnings.")
	modCmd.Flags().Bool("nocollect_code_coverage", false, "If specified, Bazel will instrument code (using offline instrumentation where")
	modCmd.Flags().Bool("nocycles", false, "Points out dependency cycles inside the displayed tree.")
	modCmd.Flags().Bool("noenforce_constraints", false, "Checks the environments each target is compatible with and reports errors if any target has dependencies that don't support the same environments")
	modCmd.Flags().Bool("noexperimental_allow_map_directory", false, "If enabled, Bazel allows the use of ctx.actions.map_directory(). This allows for the creation of actions based on the files in a directory through a user defined Starlark function and a <code>template_ctx</code> that supports basic action generation APIs.")
	modCmd.Flags().Bool("noexperimental_check_external_other_files", false, "Check for modifications made to the non-output, non-repo external files, e.g. host files.")
	modCmd.Flags().Bool("noexperimental_check_output_files", false, "Check for modifications made to the output files of a build. Consider setting this flag to false if you don't expect these files to change outside of bazel since it will speed up subsequent runs as they won't have to check a previous run's cache.")
	modCmd.Flags().Bool("noexperimental_collect_code_coverage_for_generated_files", false, "If specified, Bazel will also generate collect coverage information for generated files.")
	modCmd.Flags().Bool("noexperimental_debug_selects_always_succeed", false, "When set, `select` functions with no matching clause will return an empty value, instead")
	modCmd.Flags().Bool("noexperimental_enforce_transitive_visibility", false, "If true, enable package()s to set the transitive_visibility attribute to restrict which packages may depend on them.")
	modCmd.Flags().Bool("noexperimental_exclude_defines_from_exec_config", false, "If true, don't propagate `--define`s to the exec transition at default; only propagate")
	modCmd.Flags().Bool("noexperimental_extended_sanity_checks", false, "Enables internal validation checks to make sure that configured target implementations only access things they should. Causes a performance hit.")
	modCmd.Flags().Bool("noexperimental_remotable_source_manifests", false, "Whether to make source manifest actions remotable")
	modCmd.Flags().Bool("noexperimental_strict_fileset_output", false, "If this option is enabled, filesets will treat all output artifacts as regular files. They will not traverse directories or be sensitive to symlinks.")
	modCmd.Flags().Bool("noexperimental_throttle_action_cache_check", false, "Whether to throttle the check whether an action is cached.")
	modCmd.Flags().Bool("noexperimental_use_platforms_in_output_dir_legacy_heuristic", false, "Please only use this flag as part of a suggested migration or testing strategy. Note")
	modCmd.Flags().Bool("noexperimental_writable_outputs", false, "If true, the file permissions of action outputs are set to `0755` instead of `0555`")
	modCmd.Flags().Bool("nofetch", false, "Allows the command to fetch external dependencies. If set to false, the command will utilize any cached version of the dependency, and if none exists, the command will result in failure.")
	modCmd.Flags().Bool("noinclude_builtin", false, "Include built-in modules in the dependency graph. Disabled by default because it is quite noisy.")
	modCmd.Flags().Bool("noinclude_unused", false, "The queries will also take into account and display the unused modules, which are not")
	modCmd.Flags().Bool("noincompatible_always_include_files_in_data", false, "If true, native rules add `DefaultInfo.files` of data dependencies to their runfiles,")
	modCmd.Flags().Bool("noincompatible_auto_exec_groups", false, "When enabled, an exec groups is automatically created for each toolchain used by a rule.")
	modCmd.Flags().Bool("noincompatible_bazel_test_exec_run_under", false, "If enabled, `bazel test --run_under=//:runner` builds `//:runner` in the exec")
	modCmd.Flags().Bool("noincompatible_bep_cpu_from_platform", false, "If specified, the value of the cpu constraint (@platforms//cpu:cpu) of the target platform is used to set the Configuration.cpu and Configuration.platform_name fields in the BEP.")
	modCmd.Flags().Bool("noincompatible_check_testonly_for_output_files", false, "If enabled, check testonly for prerequisite targets that are output files by looking up the testonly of the generating rule. This matches visibility checking.")
	modCmd.Flags().Bool("noincompatible_compact_repo_mapping_manifest", false, "If enabled, the `{binary}.repo_mapping` file emits a module extension's repo mapping")
	modCmd.Flags().Bool("noincompatible_config_setting_private_default_visibility", false, "If incompatible_enforce_config_setting_visibility=false, this is a noop. Else, if this flag is false, any config_setting without an explicit visibility attribute is //visibility:public. If this flag is true, config_setting follows the same visibility logic as all other rules. See https://github.com/bazelbuild/bazel/issues/12933.")
	modCmd.Flags().Bool("noincompatible_enforce_config_setting_visibility", false, "If true, enforce config_setting visibility restrictions. If false, every config_setting is visible to every target. See https://github.com/bazelbuild/bazel/issues/12932.")
	modCmd.Flags().Bool("noincompatible_exclude_starlark_flags_from_exec_config", false, "If true, don't propagate starlark flags to the exec transition at default; only propagate starlark flags specified in `--experimental_propagate_custom_flag`.")
	modCmd.Flags().Bool("noincompatible_filegroup_runfiles_for_data", false, "If true, runfiles of targets listed in the srcs attribute are available to targets that consume the filegroup as a data dependency.")
	modCmd.Flags().Bool("noincompatible_merge_genfiles_directory", false, "If true, the genfiles directory is folded into the bin directory.")
	modCmd.Flags().Bool("noincompatible_modify_execution_info_additive", false, "When enabled, passing multiple `--modify_execution_info` flags is additive.")
	modCmd.Flags().Bool("noincompatible_target_cpu_from_platform", false, "If specified, the value of the cpu constraint (`@platforms//cpu:cpu`) of")
	modCmd.Flags().Bool("noinstrument_test_targets", false, "When coverage is enabled, specifies whether to consider instrumenting test rules.")
	modCmd.Flags().Bool("noshow_loading_progress", false, "If enabled, causes Bazel to print \"Loading package:\" messages.")
	modCmd.Flags().Bool("nostamp", false, "Stamp binaries with the date, username, hostname, workspace information, etc.")
	modCmd.Flags().Bool("nostrict_filesets", false, "If this option is enabled, filesets crossing package boundaries are reported as errors.")
	modCmd.Flags().Bool("nouse_target_platform_for_tests", false, "If true, use the target platform for running tests rather than the test exec group.")
	modCmd.Flags().Bool("noverbose", false, "The queries will also display the reason why modules were resolved to their current version (if changed). Defaults to true only for the explain query.")
	modCmd.Flags().Bool("noverbose_visibility_errors", false, "If enabled, visibility errors include additional diagnostic information.")
	modCmd.Flags().String("output", "", "The format in which the query results should be printed. Allowed values for query are:")
	modCmd.Flags().String("package_path", "", "A colon-separated list of where to look for packages. Elements beginning with '%workspace%' are relative to the enclosing workspace. If omitted or empty, the default is the output of 'bazel info default-package-path'.")
	modCmd.Flags().String("platform_suffix", "", "Specifies a suffix to be added to the configuration directory.")
	modCmd.Flags().String("run_under", "", "Prefix to insert before the executables for the `test` and `run` commands.")
	modCmd.Flags().String("scl_config", "", "Name of the scl config defined in PROJECT.scl. Note that this feature is still under development b/324119879.")
	modCmd.Flags().Bool("show_loading_progress", false, "If enabled, causes Bazel to print \"Loading package:\" messages.")
	modCmd.Flags().Bool("stamp", false, "Stamp binaries with the date, username, hostname, workspace information, etc.")
	modCmd.Flags().Bool("strict_filesets", false, "If this option is enabled, filesets crossing package boundaries are reported as errors.")
	modCmd.Flags().StringSlice("target_environment", nil, "Declares this build's target environment. Must be a label reference to an")
	modCmd.Flags().Bool("use_target_platform_for_tests", false, "If true, use the target platform for running tests rather than the test exec group.")
	modCmd.Flags().Bool("verbose", false, "The queries will also display the reason why modules were resolved to their current version (if changed). Defaults to true only for the explain query.")
	modCmd.Flags().Bool("verbose_visibility_errors", false, "If enabled, visibility errors include additional diagnostic information.")
	rootCmd.AddCommand(modCmd)
}
