# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: generate NAME
description: Generate and load a signing key-pair
flags:
    --dir=: Directory to generate key in, defaults to current directory
