# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create [OPTIONS] SECRET [file|-]
description: Create a secret from a file or STDIN as content
flags:
    --template-driver=: Template driver
    -d, --driver=: Secret driver
    -l, --label=: Secret labels
