# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: attach [OPTIONS] CONTAINER
description: Attach local standard input, output, and error streams to a running container
flags:
    --detach-keys=: Override the key sequence for detaching a container
    --no-stdin: Do not attach STDIN
    --sig-proxy: Proxy all received signals to the process
