# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: history [OPTIONS] IMAGE
description: Show the history of an image
flags:
    --format=: 'Format output using a custom template:'
    --no-trunc: Don't truncate output
    --platform=: Show history for the given platform. Formatted as "os[/arch[/variant]]" (e.g., "linux/amd64")
    -H, --human: Print sizes and dates in human readable format
    -q, --quiet: Only show image IDs
