# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm [OPTIONS] CONTAINER CHECKPOINT
aliases:
    - remove
description: Remove a checkpoint
flags:
    --checkpoint-dir=: Use a custom checkpoint storage directory
