# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create [OPTIONS] CONTEXT
description: Create a context
flags:
    --description=: Description of the context
    --docker=: set the docker endpoint
    --from=: create context from a named context
