# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: unset
description: Unset a configuration value
flags:
    -g, --global: Operation on global configuration
    -l, --local: Operation on project-local configuration
    -m, --manifest-path=: The path to `pixi.toml`, `pyproject.toml`, or the workspace directory
    -s, --system: Operation on system configuration
    -w, --workspace=: Name of the workspace
