# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: set-credentials NAME [--client-certificate=path/to/certfile] [--client-key=path/to/keyfile] [--token=bearer_token] [--username=basic_user] [--password=basic_password] [--auth-provider=provider_name] [--auth-provider-arg=key=value] [--exec-command=exec_command] [--exec-api-version=exec_api_version] [--exec-arg=arg] [--exec-env=key=value]
description: Set a user entry in kubeconfig
flags:
    --auth-provider-arg=*: '''key=value'' arguments for the auth provider'
    --auth-provider=: Auth provider for the user entry in kubeconfig
    --client-certificate=: Path to client-certificate file for the user entry in kubeconfig
    --client-key=: Path to client-key file for the user entry in kubeconfig
    --embed-certs?: Embed client cert/key for the user entry in kubeconfig
    --exec-api-version=: API version of the exec credential plugin for the user entry in kubeconfig
    --exec-arg=*: New arguments for the exec credential plugin command for the user entry in kubeconfig
    --exec-command=: Command for the exec credential plugin for the user entry in kubeconfig
    --exec-env=*: '''key=value'' environment values for the exec credential plugin'
    --exec-interactive-mode=: InteractiveMode of the exec credentials plugin for the user entry in kubeconfig
    --exec-provide-cluster-info?: ProvideClusterInfo of the exec credentials plugin for the user entry in kubeconfig
    --password=: password for the user entry in kubeconfig
    --token=: token for the user entry in kubeconfig
    --username=: username for the user entry in kubeconfig

documentation:
  command: |
    Set a user entry in kubeconfig.
    Specifying a name that already exists will merge new fields on top of existing values.
    Client-certificate flags: --client-certificate=certfile --client-key=keyfile. Bearer token flags: --token=bearer_token. Basic auth flags: --username=basic_user --password=basic_password. Bearer token and basic auth are mutually exclusive.
