# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: sign-artifacts
description: Produce artifact signatures and update repodata.json
flags:
    -h, --help: show this help message and exit
