FROM ghcr.io/carapace-sh/go:1.25.4

RUN curl -L https://github.com/goreleaser/goreleaser/releases/download/v2.13.2/goreleaser_Linux_x86_64.tar.gz \
  | tar -xvz goreleaser \
  && mv goreleaser /usr/local/bin/
