services:
  build: &base
    image: ghcr.io/carapace-sh/carapace
    command: sh -c 'sh -c "cd /carapace-bin/cmd/carapace && go generate ./... && go build -ldflags=\"-s -w\" ."'
    environment:
      CARAPACE_BRIDGES: zsh,fish,bash
      TARGET: /carapace-bin/cmd/carapace/carapace
    volumes:
      - '..:/carapace-bin/'
      - 'go:/home/circleci/go/'

  bash:
    <<: *base
    command: bash

  ble:
    <<: *base
    command: bash
    environment:
      BLE: 1
      TARGET: /carapace-bin/cmd/carapace/carapace

  elvish:
    <<: *base
    command: elvish

  fish:
    <<: *base
    command: fish
  
  ion:
    <<: *base
    command: ion
  
  nushell:
    <<: *base
    command: nu
  
  oil:
    <<: *base
    command: osh --completion-display minimal

  powershell:
    <<: *base
    command: pwsh
  
  tcsh:
    <<: *base
    command: tcsh
  
  xonsh: 
    <<: *base
    command: xonsh

  zsh:
    <<: *base
    command: zsh

  test:
    <<: *base
    working_dir: /carapace-bin
    command: go test -v ./...

  inittrace:
    <<: *base
    working_dir: /carapace-bin
    command: bash -c "GODEBUG=inittrace=1 go run ./cmd/carapace 2>&1 | grep 'init github.com/carapace-sh/carapace-bin' | awk '{print $$5\" \"$$6\" \"$$2}' | sort -r"
  
  lint:
    <<: *base
    working_dir: /carapace-bin
    command: bash -c 'go run ./cmd/caralint completers/*/cmd/*.go'
  
  fmt:
    <<: *base
    working_dir: /carapace-bin
    #  user: 1000:1000
    command: bash -c 'go run ./cmd/carafmt completers/*/cmd/*.go'

volumes:
  go:
