package chroma

import "github.com/rsteube/carapace"

// ActionStyles completes styles
//
//	abap
//	algol
func ActionStyles() carapace.Action {
	return carapace.ActionValues(
		"abap",
		"algol",
		"algol_nu",
		"arduino",
		"autumn",
		"average",
		"base16-snazzy",
		"borland",
		"bw",
		"catppuccin-frappe",
		"catppuccin-latte",
		"catppuccin-macchiato",
		"catppuccin-mocha",
		"colorful",
		"doom-one",
		"doom-one2",
		"dracula",
		"emacs",
		"friendly",
		"fruity",
		"github",
		"github-dark",
		"gruvbox",
		"gruvbox-light",
		"hr_high_contrast",
		"hrdark",
		"igor",
		"lovelace",
		"manni",
		"modus-operandi",
		"modus-vivendi",
		"monokai",
		"monokailight",
		"murphy",
		"native",
		"nord",
		"onedark",
		"onesenterprise",
		"paraiso-dark",
		"paraiso-light",
		"pastie",
		"perldoc",
		"pygments",
		"rainbow_dash",
		"rose-pine",
		"rose-pine-dawn",
		"rose-pine-moon",
		"rrt",
		"solarized-dark",
		"solarized-dark256",
		"solarized-light",
		"swapoff",
		"tango",
		"trac",
		"vim",
		"vs",
		"vulcan",
		"witchhazel",
		"xcode",
		"xcode-dark",
	).Tag("styles")
}
