package cmd

import (
	"github.com/carapace-sh/carapace"
	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "scc",
	Short: "Sloc, Cloc and Code: count lines of code in a directory with complexity estimation",
	Long:  "https://github.com/boyter/scc",
	Run:   func(cmd *cobra.Command, args []string) {},
}

func Execute() error {
	return rootCmd.Execute()
}

func init() {
	carapace.Gen(rootCmd).Standalone()

	rootCmd.Flags().Int("avg-wage", 56286, "average wage value used for basic COCOMO calculation")
	rootCmd.Flags().Bool("binary", false, "disable binary file detection")
	rootCmd.Flags().Bool("by-file", false, "display output for every file")
	rootCmd.Flags().BoolP("character", "m", false, "calculate max and mean characters per line")
	rootCmd.Flags().Bool("ci", false, "enable CI output settings where stdout is ASCII")
	rootCmd.Flags().String("cocomo-project-type", "organic", "change COCOMO model type [organic, semi-detached, embedded, custom]")
	rootCmd.Flags().String("count-as", "", "count extension as language")
	rootCmd.Flags().Bool("count-ignore", false, "allow .gitignore and .ignore files to be counted")
	rootCmd.Flags().String("currency-symbol", "$", "set currency symbol")
	rootCmd.Flags().Bool("debug", false, "enable debug output")
	rootCmd.Flags().Int("directory-walker-job-workers", 8, "maximum number of workers which will walk the directory tree")
	rootCmd.Flags().BoolP("dryness", "a", false, "calculate the DRYness of the project")
	rootCmd.Flags().Float64("eaf", 1, "effort adjustment factor derived from cost drivers")
	rootCmd.Flags().StringSlice("exclude-dir", []string{".git", ".hg", ".svn"}, "directories to exclude")
	rootCmd.Flags().StringSliceP("exclude-ext", "x", nil, "ignore file extensions")
	rootCmd.Flags().StringSliceP("exclude-file", "n", []string{"package-lock.json", "Cargo.lock", "yarn.lock", "pubspec.lock", "Podfile.lock", "pnpm-lock.yaml"}, "ignore files with matching names")
	rootCmd.Flags().Int("file-gc-count", 10000, "number of files to parse before turning the GC on")
	rootCmd.Flags().Int("file-list-queue-size", 24, "size of the queue of files found and ready to be read into memory")
	rootCmd.Flags().Int("file-process-job-workers", 24, "number of goroutine workers that process files")
	rootCmd.Flags().Int("file-summary-job-queue-size", 24, "size of the queue used to hold processed file statistics")
	rootCmd.Flags().StringP("format", "f", "tabular", "set output format")
	rootCmd.Flags().String("format-multi", "", "multiple format output overriding --format")
	rootCmd.Flags().Bool("gen", false, "identify generated files")
	rootCmd.Flags().StringSlice("generated-markers", []string{"do not edit", "<auto-generated />"}, "string markers in head of generated files")
	rootCmd.Flags().StringSliceP("include-ext", "i", nil, "limit to file extensions")
	rootCmd.Flags().Bool("include-symlinks", false, "count symlink files")
	rootCmd.Flags().BoolP("languages", "l", false, "print supported languages and extensions")
	rootCmd.Flags().Int("large-byte-count", 1000000, "number of bytes a file can contain before being removed from output")
	rootCmd.Flags().Int("large-line-count", 40000, "number of lines a file can contain before being removed from output")
	rootCmd.Flags().Bool("min", false, "identify minified files")
	rootCmd.Flags().BoolP("min-gen", "z", false, "identify minified or generated files")
	rootCmd.Flags().Int("min-gen-line-length", 255, "bytes per average line for file to be considered minified or generated")
	rootCmd.Flags().Bool("no-cocomo", false, "remove COCOMO calculation output")
	rootCmd.Flags().BoolP("no-complexity", "c", false, "skip calculation of code complexity")
	rootCmd.Flags().BoolP("no-duplicates", "d", false, "remove duplicate files from stats and output")
	rootCmd.Flags().Bool("no-gen", false, "ignore generated files in output")
	rootCmd.Flags().Bool("no-gitignore", false, "disables .gitignore file logic")
	rootCmd.Flags().Bool("no-gitmodule", false, "disables .gitmodules file logic")
	rootCmd.Flags().Bool("no-hborder", false, "remove horizontal borders between sections")
	rootCmd.Flags().Bool("no-ignore", false, "disables .ignore file logic")
	rootCmd.Flags().Bool("no-large", false, "ignore files over certain byte and line size")
	rootCmd.Flags().Bool("no-min", false, "ignore minified files in output")
	rootCmd.Flags().Bool("no-min-gen", false, "ignore minified or generated files in output")
	rootCmd.Flags().Bool("no-scc-ignore", false, "disables .sccignore file logic")
	rootCmd.Flags().Bool("no-size", false, "remove size calculation output")
	rootCmd.Flags().StringArrayP("not-match", "M", nil, "ignore files and directories matching regular expression")
	rootCmd.Flags().StringP("output", "o", "", "output filename")
	rootCmd.Flags().Float64("overhead", 2.4, "overhead multiplier for corporate overhead")
	rootCmd.Flags().BoolP("percent", "p", false, "include percentage values in output")
	rootCmd.Flags().String("remap-all", "", "inspect every file and remap by checking for a string")
	rootCmd.Flags().String("remap-unknown", "", "inspect files of unknown type and remap by checking for a string")
	rootCmd.Flags().String("size-unit", "si", "set size unit")
	rootCmd.Flags().Bool("sloccount-format", false, "print a more SLOCCount like COCOMO calculation")
	rootCmd.Flags().StringP("sort", "s", "files", "column to sort by")
	rootCmd.Flags().String("sql-project", "", "project identifier for SQL output")
	rootCmd.Flags().BoolP("trace", "t", false, "enable trace output")
	rootCmd.Flags().BoolP("uloc", "u", false, "calculate the number of unique lines of code")
	rootCmd.Flags().BoolP("verbose", "v", false, "verbose output")
	rootCmd.Flags().Bool("version", false, "version for scc")
	rootCmd.Flags().BoolP("wide", "w", false, "wider output with additional statistics")

	carapace.Gen(rootCmd).FlagCompletion(carapace.ActionMap{
		"cocomo-project-type": carapace.ActionValues("organic", "semi-detached", "embedded", "custom,"),
		"format": carapace.ActionValues(
			"tabular", "wide", "json", "json2", "csv", "csv-stream",
			"cloc-yaml", "html", "html-table", "sql", "sql-insert", "openmetrics",
		),
		"output":    carapace.ActionFiles(),
		"size-unit": carapace.ActionValues("si", "binary", "mixed", "xkcd-kb", "xkcd-kelly", "xkcd-imaginary", "xkcd-intel", "xkcd-drive", "xkcd-bakers"),
		"sort":      carapace.ActionValues("files", "name", "lines", "blanks", "code", "comments", "complexity"),
	})

	carapace.Gen(rootCmd).PositionalAnyCompletion(
		carapace.ActionFiles(),
	)
}
