# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: migrate
description: Read an older version of the kubeadm configuration API types from a file, and output the similar config object for the newer version
flags:
    --allow-experimental-api: Allow migration to experimental, unreleased APIs.
    --new-config=: Path to the resulting equivalent kubeadm config file using the new API version. Optional, if not specified output will be sent to STDOUT.
    --old-config=: Path to the kubeadm config file that is using an old API version and should be converted. This flag is mandatory.
