# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: update
description: Update deprecated config settings
flags:
    --output=: Output migrated config (- for stdout)
    -h, --help: Print help (see more with '--help')
completion:
    flag:
        C:
            - $files
        config:
            - $files
        output:
            - $files
