# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get
description: Get log file paths
flags:
    --branch=: Target branch (defaults to current)
    --hook=: Get path for a specific log file
    -h, --help: Print help (see more with '--help')
