// Code generated from mise.usage.kdl; DO NOT EDIT.
package cmd

var rootFlagSpecs = []flagSpec{
	flagSpec{spec: "-C --cd", description: "Change directory before running command", value: true, persistent: true},
	flagSpec{spec: "-E --env", description: "Set the environment for loading `mise.<ENV>.toml`", value: true, array: true, persistent: true},
	flagSpec{spec: "-j --jobs", description: "How many jobs to run in parallel [default: 8]", value: true, persistent: true},
	flagSpec{spec: "-q --quiet", description: "Suppress non-error messages", persistent: true},
	flagSpec{spec: "-v --verbose", description: "Show extra output (use -vv for even more)", array: true, count: true, persistent: true},
	flagSpec{spec: "-y --yes", description: "Answer yes to all confirmation prompts", persistent: true},
	flagSpec{spec: "--no-config", description: "Do not load any config files"},
	flagSpec{spec: "--no-env", description: "Do not load environment variables from config files"},
	flagSpec{spec: "--no-hooks", description: "Do not execute hooks from config files"},
	flagSpec{spec: "--output", value: true},
	flagSpec{spec: "--raw", description: "Read/write directly to stdin/stdout/stderr instead of by line", persistent: true},
	flagSpec{spec: "--locked", description: "Require lockfile URLs to be present during installation", persistent: true},
	flagSpec{spec: "--silent", description: "Suppress all task output and mise non-error messages", persistent: true},
}

var commandSpecs = []commandSpec{
	{
		path:        []string{"activate"},
		description: "Initializes mise in the current shell session",
		flags: []flagSpec{
			flagSpec{spec: "-q --quiet", description: "Suppress non-error messages"},
			flagSpec{spec: "--no-hook-env", description: "Do not automatically call hook-env"},
			flagSpec{spec: "--shims", description: "Use shims instead of modifying PATH\\nEffectively the same as:"},
		},
	},
	{
		path:        []string{"tool-alias"},
		description: "Manage tool version aliases.",
		aliases:     []string{"alias", "aliases"},
		flags: []flagSpec{
			flagSpec{spec: "-p --plugin", description: "filter aliases by plugin", value: true},
			flagSpec{spec: "--no-header", description: "Don't show table header"},
		},
	},
	{
		path:        []string{"tool-alias", "get"},
		description: "Show an alias for a plugin",
	},
	{
		path:        []string{"tool-alias", "ls"},
		description: "List tool version aliases\\nShows the aliases that can be specified.\\nThese can come from user config or from plugins in `bin/list-aliases`.",
		aliases:     []string{"list"},
		flags: []flagSpec{
			flagSpec{spec: "--no-header", description: "Don't show table header"},
		},
	},
	{
		path:        []string{"tool-alias", "set"},
		description: "Add/update an alias for a backend/plugin",
		aliases:     []string{"add", "create"},
	},
	{
		path:        []string{"tool-alias", "unset"},
		description: "Clears an alias for a backend/plugin",
		aliases:     []string{"rm", "remove", "delete", "del"},
	},
	{
		path:        []string{"backends"},
		description: "Manage backends",
		aliases:     []string{"b", "backend", "backend-list"},
	},
	{
		path:        []string{"backends", "ls"},
		description: "List built-in backends",
		aliases:     []string{"list"},
	},
	{
		path:        []string{"bin-paths"},
		description: "List all the active runtime bin paths",
		flags: []flagSpec{
			flagSpec{spec: "--bin-names", description: "Output executable names instead of bin directories"},
			flagSpec{spec: "-J --json", description: "Output executable entries in JSON format (implies --bin-names)"},
		},
	},
	{
		path:        []string{"cache"},
		description: "Manage the mise cache",
	},
	{
		path:        []string{"cache", "clear"},
		description: "Deletes all cache files in mise",
		aliases:     []string{"c", "clean"},
	},
	{
		path:        []string{"cache", "path"},
		description: "Show the cache directory path",
		aliases:     []string{"dir"},
	},
	{
		path:        []string{"cache", "prune"},
		description: "Removes stale mise cache files",
		aliases:     []string{"p"},
		flags: []flagSpec{
			flagSpec{spec: "-v --verbose", description: "Show pruned files", array: true, count: true},
			flagSpec{spec: "--dry-run", description: "Just show what would be pruned"},
		},
	},
	{
		path:        []string{"completion"},
		description: "Generate shell completions",
		aliases:     []string{"complete", "completions"},
		flags: []flagSpec{
			flagSpec{spec: "--include-bash-completion-lib", description: "Include the bash completion library in the bash completion script"},
		},
	},
	{
		path:        []string{"config"},
		description: "Manage config files",
		aliases:     []string{"cfg", "toml"},
		flags: []flagSpec{
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
			flagSpec{spec: "--no-header", description: "Do not print table header"},
			flagSpec{spec: "--tracked-configs", description: "List all tracked config files"},
		},
	},
	{
		path:        []string{"config", "get"},
		description: "Display the value of a setting in a mise.toml file",
		flags: []flagSpec{
			flagSpec{spec: "-f --file", description: "The path to the mise.toml file to edit", value: true},
		},
	},
	{
		path:        []string{"config", "ls"},
		description: "List config files currently in use",
		aliases:     []string{"list"},
		flags: []flagSpec{
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
			flagSpec{spec: "--no-header", description: "Do not print table header"},
			flagSpec{spec: "--tracked-configs", description: "List all tracked config files"},
		},
	},
	{
		path:        []string{"config", "set"},
		description: "Set the value of a setting in a mise.toml file",
		flags: []flagSpec{
			flagSpec{spec: "-f --file", description: "The path to the mise.toml file to edit", value: true},
			flagSpec{spec: "-t --type", value: true, choices: []string{"infer", "string", "integer", "float", "bool", "list", "set"}},
		},
	},
	{
		path:        []string{"deactivate"},
		description: "Disable mise for current shell session",
	},
	{
		path:        []string{"doctor"},
		description: "Check mise installation for possible problems",
		aliases:     []string{"dr"},
		flags: []flagSpec{
			flagSpec{spec: "-J --json"},
		},
	},
	{
		path:        []string{"doctor", "path"},
		description: "Print the current PATH entries mise is providing",
		aliases:     []string{"paths"},
		flags: []flagSpec{
			flagSpec{spec: "-f --full", description: "Print all entries including those not provided by mise"},
		},
	},
	{
		path:        []string{"en"},
		description: "Starts a new shell with the mise environment built from the current configuration",
		flags: []flagSpec{
			flagSpec{spec: "-s --shell", description: "Shell to start", value: true},
		},
	},
	{
		path:        []string{"env"},
		description: "Exports env vars to activate mise a single time",
		aliases:     []string{"e"},
		flags: []flagSpec{
			flagSpec{spec: "-D --dotenv", description: "Output in dotenv format"},
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
			flagSpec{spec: "-s --shell", description: "Shell type to generate environment variables for", value: true, choices: []string{"bash", "elvish", "fish", "nu", "xonsh", "zsh", "pwsh"}},
			flagSpec{spec: "--json-extended", description: "Output in JSON format with additional information (source, tool)"},
			flagSpec{spec: "--redacted", description: "Only show redacted environment variables"},
			flagSpec{spec: "--values", description: "Only show values of environment variables"},
		},
	},
	{
		path:        []string{"exec"},
		description: "Execute a command with tool(s) set",
		aliases:     []string{"x"},
		flags: []flagSpec{
			flagSpec{spec: "-c --command", description: "Command string to execute", value: true},
			flagSpec{spec: "-j --jobs", description: "Number of jobs to run in parallel\\n[default: 4]", value: true},
			flagSpec{spec: "--allow-env", description: "[experimental] Allow specific env var through (implies --deny-env for everything else)\\nSupports wildcards, e.g. --allow-env='MYAPP_*'", value: true, array: true},
			flagSpec{spec: "--allow-net", description: "[experimental] Allow network to specific host (implies --deny-net for everything else)\\nmacOS only in v1; on Linux falls back to allowing all network", value: true, array: true},
			flagSpec{spec: "--allow-read", description: "[experimental] Allow reads from specific path (implies --deny-read for everything else)", value: true, array: true},
			flagSpec{spec: "--allow-write", description: "[experimental] Allow writes to specific path (implies --deny-write for everything else)", value: true, array: true},
			flagSpec{spec: "--deny-all", description: "[experimental] Block reads, writes, network, and env vars"},
			flagSpec{spec: "--deny-env", description: "[experimental] Block env var inheritance (only PATH, HOME, USER, SHELL, TERM, LANG pass through)"},
			flagSpec{spec: "--deny-net", description: "[experimental] Block all network access"},
			flagSpec{spec: "--deny-read", description: "[experimental] Block filesystem reads (system libs and tool dirs still accessible)"},
			flagSpec{spec: "--deny-write", description: "[experimental] Block all filesystem writes"},
			flagSpec{spec: "--fresh-env", description: "Bypass the environment cache and recompute the environment"},
			flagSpec{spec: "--no-deps", description: "Skip automatic dependency preparation"},
			flagSpec{spec: "--raw", description: "Directly pipe stdin/stdout/stderr from plugin to user Sets --jobs=1"},
		},
	},
	{
		path:        []string{"fmt"},
		description: "Formats mise.toml",
		flags: []flagSpec{
			flagSpec{spec: "-a --all", description: "Format all files from the current directory"},
			flagSpec{spec: "-c --check", description: "Check if the configs are formatted, no formatting is done"},
			flagSpec{spec: "-s --stdin", description: "Read config from stdin and write its formatted version into stdout"},
		},
	},
	{
		path:        []string{"generate"},
		description: "Generate files for various tools/services",
		aliases:     []string{"gen", "g"},
	},
	{
		path:        []string{"generate", "bootstrap"},
		description: "Generate a script to download+execute mise",
		flags: []flagSpec{
			flagSpec{spec: "-l --localize", description: "Sandboxes mise internal directories like MISE_DATA_DIR and MISE_CACHE_DIR into a `.mise` directory in the project"},
			flagSpec{spec: "-V --version", description: "Specify mise version to fetch", value: true},
			flagSpec{spec: "-w --write", description: "instead of outputting the script to stdout, write to a file and make it executable", value: true},
			flagSpec{spec: "--localized-dir", description: "Directory to put localized data into", value: true},
		},
	},
	{
		path:        []string{"generate", "config"},
		description: "Generate a mise.toml file",
		flags: []flagSpec{
			flagSpec{spec: "-n --dry-run", description: "Show what would be generated without writing to file"},
			flagSpec{spec: "-t --tool-versions", description: "Path to a .tool-versions file to import tools from", value: true},
		},
	},
	{
		path:        []string{"generate", "devcontainer"},
		description: "Generate a devcontainer to execute mise",
		flags: []flagSpec{
			flagSpec{spec: "-i --image", description: "The image to use for the devcontainer", value: true},
			flagSpec{spec: "-m --mount-mise-data", description: "Bind the mise-data-volume to the devcontainer"},
			flagSpec{spec: "-n --name", description: "The name of the devcontainer", value: true},
			flagSpec{spec: "-w --write", description: "write to .devcontainer/devcontainer.json"},
		},
	},
	{
		path:        []string{"generate", "git-pre-commit"},
		description: "Generate a git pre-commit hook",
		aliases:     []string{"pre-commit"},
		flags: []flagSpec{
			flagSpec{spec: "-t --task", description: "The task to run when the pre-commit hook is triggered", value: true},
			flagSpec{spec: "-w --write", description: "write to .git/hooks/pre-commit and make it executable"},
			flagSpec{spec: "--hook", description: "Which hook to generate (saves to .git/hooks/$hook)", value: true},
		},
	},
	{
		path:        []string{"generate", "github-action"},
		description: "Generate a GitHub Action workflow file",
		flags: []flagSpec{
			flagSpec{spec: "-t --task", description: "The task to run when the workflow is triggered", value: true},
			flagSpec{spec: "-w --write", description: "write to .github/workflows/$name.yml"},
			flagSpec{spec: "--name", description: "the name of the workflow to generate", value: true},
		},
	},
	{
		path:        []string{"generate", "task-docs"},
		description: "Generate documentation for tasks in a project",
		flags: []flagSpec{
			flagSpec{spec: "-i --inject", description: "inserts the documentation into an existing file"},
			flagSpec{spec: "-I --index", description: "write only an index of tasks, intended for use with `--multi`"},
			flagSpec{spec: "-m --multi", description: "render each task as a separate document, requires `--output` to be a directory"},
			flagSpec{spec: "-o --output", description: "writes the generated docs to a file/directory", value: true},
			flagSpec{spec: "-r --root", description: "root directory to search for tasks", value: true},
			flagSpec{spec: "-s --style", value: true, choices: []string{"simple", "detailed"}},
		},
	},
	{
		path:        []string{"generate", "task-stubs"},
		description: "Generates shims to run mise tasks",
		flags: []flagSpec{
			flagSpec{spec: "-d --dir", description: "Directory to create task stubs inside of", value: true},
			flagSpec{spec: "-m --mise-bin", description: "Path to a mise bin to use when running the task stub.", value: true},
		},
	},
	{
		path:        []string{"generate", "tool-stub"},
		description: "Generate a tool stub for HTTP-based tools",
		flags: []flagSpec{
			flagSpec{spec: "-b --bin", description: "Binary path within the extracted archive", value: true},
			flagSpec{spec: "--bootstrap", description: "Wrap stub in a bootstrap script that installs mise if not already present"},
			flagSpec{spec: "--bootstrap-version", description: "Specify mise version for the bootstrap script", value: true},
			flagSpec{spec: "--fetch", description: "Fetch checksums and sizes for an existing tool stub file"},
			flagSpec{spec: "--http", description: "HTTP backend type to use", value: true},
			flagSpec{spec: "--lock", description: "Resolve and embed lockfile data (exact version + platform URLs/checksums) into an existing stub file for reproducible installs without runtime API calls"},
			flagSpec{spec: "--platform-bin", description: "Platform-specific binary paths in the format platform:path", value: true, array: true},
			flagSpec{spec: "--platform-url", description: "Platform-specific URLs in the format platform:url or just url (auto-detect platform)", value: true, array: true},
			flagSpec{spec: "--skip-download", description: "Skip downloading for checksum and binary path detection (faster but less informative)"},
			flagSpec{spec: "-u --url", description: "URL for downloading the tool", value: true},
			flagSpec{spec: "--version", description: "Version of the tool", value: true},
		},
	},
	{
		path:        []string{"implode"},
		description: "Removes mise CLI and all related data",
		flags: []flagSpec{
			flagSpec{spec: "-n --dry-run", description: "List directories that would be removed without actually removing them"},
			flagSpec{spec: "--config", description: "Also remove config directory"},
		},
	},
	{
		path:        []string{"edit"},
		description: "Edit mise.toml interactively",
		flags: []flagSpec{
			flagSpec{spec: "-n --dry-run", description: "Show what would be generated without writing to file"},
			flagSpec{spec: "-t --tool-versions", description: "Path to a .tool-versions file to import tools from", value: true},
		},
	},
	{
		path:        []string{"install"},
		description: "Install a tool version",
		aliases:     []string{"i"},
		flags: []flagSpec{
			flagSpec{spec: "-f --force", description: "Force reinstall even if already installed"},
			flagSpec{spec: "-j --jobs", description: "Number of jobs to run in parallel\\n[default: 4]", value: true},
			flagSpec{spec: "-n --dry-run", description: "Show what would be installed without actually installing"},
			flagSpec{spec: "-v --verbose", description: "Show installation output", array: true, count: true},
			flagSpec{spec: "--before", description: "Only install versions released before this date", value: true},
			flagSpec{spec: "--dry-run-code", description: "Like --dry-run but exits with code 1 if there are tools to install"},
			flagSpec{spec: "--raw", description: "Directly pipe stdin/stdout/stderr from plugin to user Sets --jobs=1"},
			flagSpec{spec: "--shared", description: "[experimental] Install tool(s) to a shared directory", value: true},
			flagSpec{spec: "--system", description: "[experimental] Install tool(s) to the system-wide shared directory"},
		},
	},
	{
		path:        []string{"install-into"},
		description: "Install a tool version to a specific path",
	},
	{
		path:        []string{"latest"},
		description: "Gets the latest available version for a plugin",
		flags: []flagSpec{
			flagSpec{spec: "-i --installed", description: "Show latest installed instead of available version"},
			flagSpec{spec: "--before", description: "Only consider versions released before this date", value: true},
		},
	},
	{
		path:        []string{"link"},
		description: "Symlinks a tool version into mise",
		aliases:     []string{"ln"},
		flags: []flagSpec{
			flagSpec{spec: "-f --force", description: "Overwrite an existing tool version if it exists"},
		},
	},
	{
		path:        []string{"lock"},
		description: "Update lockfile checksums and URLs for all specified platforms",
		flags: []flagSpec{
			flagSpec{spec: "-g --global", description: "Target only global config lockfiles (~/.config/mise/mise.lock and system config)\\nBy default, only the active project config root is locked"},
			flagSpec{spec: "-j --jobs", description: "Number of jobs to run in parallel", value: true},
			flagSpec{spec: "-n --dry-run", description: "Show what would be updated without making changes"},
			flagSpec{spec: "-p --platform", description: "Comma-separated list of platforms to target\\ne.g.: linux-x64,macos-arm64,windows-x64\\nIf not specified, all platforms already in lockfile will be updated", value: true, array: true},
			flagSpec{spec: "--local", description: "Update mise.local.lock instead of mise.lock\\nUse for tools defined in .local.toml configs"},
			flagSpec{spec: "--minimum-release-age", description: "Only lock versions released before this age or date", value: true},
		},
	},
	{
		path:        []string{"ls"},
		description: "List installed and active tool versions",
		aliases:     []string{"list"},
		flags: []flagSpec{
			flagSpec{spec: "-c --current", description: "Only show tool versions currently specified in a mise.toml"},
			flagSpec{spec: "-g --global", description: "Only show tool versions currently specified in the global mise.toml"},
			flagSpec{spec: "-i --installed", description: "Only show tool versions that are installed (Hides tools defined in mise.toml but not installed)"},
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
			flagSpec{spec: "-l --local", description: "Only show tool versions currently specified in the local mise.toml"},
			flagSpec{spec: "-m --missing", description: "Display missing tool versions"},
			flagSpec{spec: "--all-sources", description: "Display all tracked config sources for tools"},
			flagSpec{spec: "--no-header", description: "Don't display headers"},
			flagSpec{spec: "--outdated", description: "Display whether a version is outdated"},
			flagSpec{spec: "--prefix", description: "Display versions matching this prefix", value: true},
			flagSpec{spec: "--prunable", description: "List only tools that can be pruned with `mise prune`"},
		},
	},
	{
		path:        []string{"ls-remote"},
		description: "List runtime versions available for install.",
		aliases:     []string{"list-all", "list-remote"},
		flags: []flagSpec{
			flagSpec{spec: "--all", description: "Show all installed plugins and versions"},
			flagSpec{spec: "--minimum-release-age", description: "Only show versions released before this age or date", value: true},
			flagSpec{spec: "-J --json", description: "Output in JSON format (includes version metadata like created_at timestamps when available)"},
			flagSpec{spec: "--no-versions-host", description: "Disable checking the mise-versions host"},
			flagSpec{spec: "--prerelease", description: "Include pre-release versions in the output for backends that report\\nupstream prerelease metadata or opt in to regex-based prerelease\\ndetection. Equivalent to setting `MISE_PRERELEASES=1` or the\\n`prereleases` setting for the duration of this command."},
			flagSpec{spec: "--strict-metadata", description: "Fail if release metadata fetches fail"},
		},
	},
	{
		path:        []string{"mcp"},
		description: "[experimental] Run Model Context Protocol (MCP) server",
	},
	{
		path:        []string{"oci"},
		description: "[experimental] Build OCI container images from a mise.toml",
	},
	{
		path:        []string{"oci", "build"},
		description: "[experimental] Build an OCI image from the current mise.toml",
		flags: []flagSpec{
			flagSpec{spec: "-o --output", description: "Output directory for the OCI image layout", value: true},
			flagSpec{spec: "--from", description: "Base image reference (overrides [oci].from and the oci.default_from setting)", value: true},
			flagSpec{spec: "--include-global", description: "Also include tools from the global / system config (default: project-only)"},
			flagSpec{spec: "-t --tag", description: "Tag to record in the image index (the org.opencontainers.image.ref.name annotation)", value: true},
			flagSpec{spec: "--mount-point", description: "Where to place tool installs inside the image (default: /mise)", value: true},
			flagSpec{spec: "--no-mise", description: "Do not embed the currently-running mise binary at /usr/local/bin/mise"},
		},
	},
	{
		path:        []string{"oci", "push"},
		description: "[experimental] Build an OCI image and push it to a registry",
		flags: []flagSpec{
			flagSpec{spec: "--from", description: "Base image for the build (ignored with --image-dir)", value: true},
			flagSpec{spec: "--image-dir", description: "Push an already-built OCI image layout (skip the build step)", value: true},
			flagSpec{spec: "--include-global", description: "Also include tools from the global / system config (default: project-only)"},
			flagSpec{spec: "--mount-point", description: "Override in-image mount point (ignored with --image-dir)", value: true},
			flagSpec{spec: "--no-mise", description: "Don't embed the mise binary (ignored with --image-dir)"},
			flagSpec{spec: "--tool", description: "Force the push tool (`auto`, `skopeo`, `crane`). Default `auto`", value: true, choices: []string{"auto", "skopeo", "crane"}},
		},
	},
	{
		path:        []string{"oci", "run"},
		description: "[experimental] Build an OCI image from the current mise.toml and run a command in it",
		flags: []flagSpec{
			flagSpec{spec: "--engine", description: "Container engine to use (`auto`, `podman`, or `docker`)", value: true, choices: []string{"auto", "podman", "docker"}},
			flagSpec{spec: "--from", description: "Base image reference for the build (ignored with --image-dir)", value: true},
			flagSpec{spec: "--image-dir", description: "Use an already-built OCI image layout instead of building fresh", value: true},
			flagSpec{spec: "--include-global", description: "Also include tools from the global / system config (default: project-only)"},
			flagSpec{spec: "--keep", description: "Keep the loaded image in the engine's storage after the run"},
			flagSpec{spec: "--mount-point", description: "Override in-image mount point (ignored with --image-dir)", value: true},
			flagSpec{spec: "--no-mise", description: "Don't embed the mise binary (ignored with --image-dir)"},
			flagSpec{spec: "--volume", description: "Bind-mount a host path (repeatable, `HOST:CONTAINER[:MODE]`)", value: true, array: true},
			flagSpec{spec: "-e --env", description: "Set environment variable in the container (repeatable, `KEY=VAL`)", value: true, array: true},
			flagSpec{spec: "-i --interactive", description: "Run interactively (pass `-i` to the engine)"},
			flagSpec{spec: "-t --tty", description: "Allocate a TTY (pass `-t` to the engine)"},
			flagSpec{spec: "-w --workdir", description: "Working directory inside the container", value: true},
		},
	},
	{
		path:        []string{"outdated"},
		description: "Shows outdated tool versions",
		flags: []flagSpec{
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
			flagSpec{spec: "-l --bump", description: "Compares against the latest versions available, not what matches the current config"},
			flagSpec{spec: "--inactive", description: "Show outdated tools including installed-but-inactive tools not present in the current config"},
			flagSpec{spec: "--local", description: "Only show outdated tools defined in local config files"},
			flagSpec{spec: "--no-header", description: "Don't show table header"},
		},
	},
	{
		path:        []string{"plugins"},
		description: "Manage plugins",
		aliases:     []string{"p", "plugin", "plugin-list"},
		flags: []flagSpec{
			flagSpec{spec: "-c --core", description: "The built-in plugins only\\nNormally these are not shown"},
			flagSpec{spec: "-u --urls", description: "Show the git url for each plugin\\ne.g.: https://github.com/mise-plugins/vfox-cmake.git"},
			flagSpec{spec: "--user", description: "List installed plugins"},
		},
	},
	{
		path:        []string{"plugins", "install"},
		description: "Install a plugin",
		aliases:     []string{"i", "a", "add"},
		flags: []flagSpec{
			flagSpec{spec: "-a --all", description: "Install all missing plugins\\nThis will only install plugins that have matching shorthands.\\ni.e.: they don't need the full git repo url"},
			flagSpec{spec: "-f --force", description: "Reinstall even if plugin exists"},
			flagSpec{spec: "-j --jobs", description: "Number of jobs to run in parallel", value: true},
			flagSpec{spec: "-v --verbose", description: "Show installation output", array: true, count: true},
		},
	},
	{
		path:        []string{"plugins", "link"},
		description: "Symlinks a plugin into mise",
		aliases:     []string{"ln"},
		flags: []flagSpec{
			flagSpec{spec: "-f --force", description: "Overwrite existing plugin"},
		},
	},
	{
		path:        []string{"plugins", "ls"},
		description: "List installed plugins",
		aliases:     []string{"list"},
		flags: []flagSpec{
			flagSpec{spec: "-o --outdated", description: "Show plugins with available updates\\nChecks the remote for newer versions and only displays plugins that are outdated"},
			flagSpec{spec: "-u --urls", description: "Show the git url for each plugin\\ne.g.: https://github.com/mise-plugins/vfox-cmake.git"},
		},
	},
	{
		path:        []string{"plugins", "ls-remote"},
		description: "List all available remote plugins",
		aliases:     []string{"list-remote", "list-all"},
		flags: []flagSpec{
			flagSpec{spec: "-u --urls", description: "Show the git url for each plugin e.g.: https://github.com/mise-plugins/mise-poetry.git"},
			flagSpec{spec: "--only-names", description: "Only show the name of each plugin by default it will show a \"*\" next to installed plugins"},
		},
	},
	{
		path:        []string{"plugins", "uninstall"},
		description: "Removes a plugin",
		aliases:     []string{"remove", "rm"},
		flags: []flagSpec{
			flagSpec{spec: "-a --all", description: "Remove all plugins"},
			flagSpec{spec: "-p --purge", description: "Also remove the plugin's installs, downloads, and cache"},
		},
	},
	{
		path:        []string{"plugins", "update"},
		description: "Updates a plugin to the latest version",
		aliases:     []string{"up", "upgrade"},
		flags: []flagSpec{
			flagSpec{spec: "-j --jobs", description: "Number of jobs to run in parallel\\nDefault: 4", value: true},
		},
	},
	{
		path:        []string{"deps"},
		description: "[experimental] Manage project dependencies",
		aliases:     []string{"dep", "prepare"},
		flags: []flagSpec{
			flagSpec{spec: "--explain", description: "Show why a provider is fresh or stale (requires a provider argument)"},
			flagSpec{spec: "-f --force", description: "Force run all deps steps even if outputs are fresh"},
			flagSpec{spec: "-n --dry-run", description: "Only check if deps install is needed, don't run commands"},
			flagSpec{spec: "--list", description: "Show what deps providers are available"},
			flagSpec{spec: "--only", description: "Run specific deps rule(s) only", value: true, array: true},
			flagSpec{spec: "--skip", description: "Skip specific deps rule(s)", value: true, array: true},
		},
	},
	{
		path:        []string{"deps", "add"},
		description: "Add a dependency",
		flags: []flagSpec{
			flagSpec{spec: "-D --dev", description: "Add as a development dependency"},
		},
	},
	{
		path:        []string{"deps", "install"},
		description: "Install all project dependencies",
		flags: []flagSpec{
			flagSpec{spec: "--explain", description: "Show why a provider is fresh or stale (requires a provider argument)"},
			flagSpec{spec: "-f --force", description: "Force run all deps steps even if outputs are fresh"},
			flagSpec{spec: "-n --dry-run", description: "Only check if deps install is needed, don't run commands"},
			flagSpec{spec: "--list", description: "Show what deps providers are available"},
			flagSpec{spec: "--only", description: "Run specific deps rule(s) only", value: true, array: true},
			flagSpec{spec: "--skip", description: "Skip specific deps rule(s)", value: true, array: true},
		},
	},
	{
		path:        []string{"deps", "remove"},
		description: "Remove a dependency",
	},
	{
		path:        []string{"prune"},
		description: "Delete unused versions of tools",
		flags: []flagSpec{
			flagSpec{spec: "-n --dry-run", description: "Do not actually delete anything"},
			flagSpec{spec: "--configs", description: "Prune only tracked and trusted configuration links that point to non-existent configurations"},
			flagSpec{spec: "--dry-run-code", description: "Like --dry-run but exits with code 1 if there are tools to prune"},
			flagSpec{spec: "--tools", description: "Prune only unused versions of tools"},
		},
	},
	{
		path:        []string{"registry"},
		description: "List available tools to install",
		flags: []flagSpec{
			flagSpec{spec: "-b --backend", description: "Show only tools for this backend", value: true},
			flagSpec{spec: "--hide-aliased", description: "Hide aliased tools"},
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
			flagSpec{spec: "--security", description: "Include security features for each tool's backends in JSON output"},
		},
	},
	{
		path:        []string{"reshim"},
		description: "Creates new shims based on bin paths from currently installed tools.",
		flags: []flagSpec{
			flagSpec{spec: "-f --force", description: "Removes all shims before reshimming"},
		},
	},
	{
		path:        []string{"run"},
		description: "Run task(s)",
		aliases:     []string{"r"},
		flags: []flagSpec{
			flagSpec{spec: "-c --continue-on-error", description: "Continue running tasks even if one fails"},
			flagSpec{spec: "-C --cd", description: "Change to this directory before executing the command", value: true},
			flagSpec{spec: "-f --force", description: "Force the tasks to run even if outputs are up to date"},
			flagSpec{spec: "-j --jobs", description: "Number of tasks to run in parallel\\n[default: 4]\\nConfigure with `jobs` config or `MISE_JOBS` env var", value: true},
			flagSpec{spec: "-n --dry-run", description: "Don't actually run the task(s), just print them in order of execution"},
			flagSpec{spec: "-o --output", description: "Change how tasks information is output when running tasks", value: true},
			flagSpec{spec: "-q --quiet", description: "Don't show extra output"},
			flagSpec{spec: "-r --raw", description: "Read/write directly to stdin/stdout/stderr instead of by line\\nRedactions are not applied with this option\\nConfigure with `raw` config or `MISE_RAW` env var"},
			flagSpec{spec: "-s --shell", description: "Shell to use to run toml tasks", value: true},
			flagSpec{spec: "-S --silent", description: "Don't show any output except for errors"},
			flagSpec{spec: "-t --tool", description: "Tool(s) to run in addition to what is in mise.toml files e.g.: node@20 python@3.10", value: true, array: true},
			flagSpec{spec: "--allow-env", description: "[experimental] Allow specific env var through (implies --deny-env for everything else)\\nSupports wildcards, e.g. --allow-env='MYAPP_*'", value: true, array: true},
			flagSpec{spec: "--allow-net", description: "[experimental] Allow network to specific host (implies --deny-net for everything else)", value: true, array: true},
			flagSpec{spec: "--allow-read", description: "[experimental] Allow reads from specific path (implies --deny-read for everything else)", value: true, array: true},
			flagSpec{spec: "--allow-write", description: "[experimental] Allow writes to specific path (implies --deny-write for everything else)", value: true, array: true},
			flagSpec{spec: "--deny-all", description: "[experimental] Block reads, writes, network, and env vars"},
			flagSpec{spec: "--deny-env", description: "[experimental] Block env var inheritance (only PATH, HOME, USER, SHELL, TERM, LANG pass through)"},
			flagSpec{spec: "--deny-net", description: "[experimental] Block all network access"},
			flagSpec{spec: "--deny-read", description: "[experimental] Block filesystem reads (system libs and tool dirs still accessible)"},
			flagSpec{spec: "--deny-write", description: "[experimental] Block all filesystem writes"},
			flagSpec{spec: "--fresh-env", description: "Bypass the environment cache and recompute the environment"},
			flagSpec{spec: "--no-cache", description: "Do not use cache on remote tasks"},
			flagSpec{spec: "--no-deps", description: "Skip automatic dependency preparation"},
			flagSpec{spec: "--no-timings", description: "Hides elapsed time after each task completes"},
			flagSpec{spec: "--skip-deps", description: "Run only the specified tasks skipping all dependencies"},
			flagSpec{spec: "--skip-tools", description: "Skip installing tools before running tasks"},
			flagSpec{spec: "--timeout", description: "Timeout for the task to complete\\ne.g.: 30s, 5m", value: true},
		},
	},
	{
		path:        []string{"search"},
		description: "Search for tools in the registry",
		flags: []flagSpec{
			flagSpec{spec: "-i --interactive", description: "Show interactive search"},
			flagSpec{spec: "-m --match-type", description: "Match type: equal, contains, or fuzzy", value: true, choices: []string{"equal", "contains", "fuzzy"}},
			flagSpec{spec: "--no-header", description: "Don't display headers"},
		},
	},
	{
		path:        []string{"self-update"},
		description: "Updates mise itself.",
		flags: []flagSpec{
			flagSpec{spec: "-f --force", description: "Update even if already up to date"},
			flagSpec{spec: "-y --yes", description: "Skip confirmation prompt"},
			flagSpec{spec: "--no-plugins", description: "Disable auto-updating plugins"},
		},
	},
	{
		path:        []string{"set"},
		description: "Set environment variables in mise.toml",
		aliases:     []string{"ev", "env-vars"},
		flags: []flagSpec{
			flagSpec{spec: "-E --env", description: "Create/modify an environment-specific config file like .mise.<env>.toml", value: true},
			flagSpec{spec: "-g --global", description: "Set the environment variable in the global config file"},
			flagSpec{spec: "--age-encrypt", description: "[experimental] Encrypt the value with age before storing"},
			flagSpec{spec: "--age-key-file", description: "[experimental] Age identity file for encryption", value: true},
			flagSpec{spec: "--age-recipient", description: "[experimental] Age recipient (x25519 public key) for encryption", value: true, array: true},
			flagSpec{spec: "--age-ssh-recipient", description: "[experimental] SSH recipient (public key or path) for age encryption", value: true, array: true},
			flagSpec{spec: "--file", description: "The TOML file to update", value: true},
			flagSpec{spec: "--no-redact", description: "Show raw values instead of redacting secrets"},
			flagSpec{spec: "--prompt", description: "Prompt for environment variable values"},
			flagSpec{spec: "--stdin", description: "Read the value from stdin (for multiline input)"},
		},
	},
	{
		path:        []string{"settings"},
		description: "Manage settings",
		flags: []flagSpec{
			flagSpec{spec: "-a --all", description: "List all settings"},
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
			flagSpec{spec: "-l --local", description: "Use the local config file instead of the global one", persistent: true},
			flagSpec{spec: "-T --toml", description: "Output in TOML format"},
			flagSpec{spec: "--json-extended", description: "Output in JSON format with sources"},
		},
	},
	{
		path:        []string{"settings", "add"},
		description: "Adds a setting to the configuration file",
		flags: []flagSpec{
			flagSpec{spec: "-l --local", description: "Use the local config file instead of the global one"},
		},
	},
	{
		path:        []string{"settings", "get"},
		description: "Show a current setting",
		flags: []flagSpec{
			flagSpec{spec: "-l --local", description: "Use the local config file instead of the global one"},
		},
	},
	{
		path:        []string{"settings", "ls"},
		description: "Show current settings",
		aliases:     []string{"list"},
		flags: []flagSpec{
			flagSpec{spec: "-a --all", description: "List all settings"},
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
			flagSpec{spec: "-l --local", description: "Use the local config file instead of the global one", persistent: true},
			flagSpec{spec: "-T --toml", description: "Output in TOML format"},
			flagSpec{spec: "--json-extended", description: "Output in JSON format with sources"},
		},
	},
	{
		path:        []string{"settings", "set"},
		description: "Add/update a setting",
		aliases:     []string{"create"},
		flags: []flagSpec{
			flagSpec{spec: "-l --local", description: "Use the local config file instead of the global one"},
		},
	},
	{
		path:        []string{"settings", "unset"},
		description: "Clears a setting",
		aliases:     []string{"rm", "remove", "delete", "del"},
		flags: []flagSpec{
			flagSpec{spec: "-l --local", description: "Use the local config file instead of the global one"},
		},
	},
	{
		path:        []string{"shell"},
		description: "Sets a tool version for the current session.",
		aliases:     []string{"sh"},
		flags: []flagSpec{
			flagSpec{spec: "-j --jobs", description: "Number of jobs to run in parallel\\n[default: 4]", value: true},
			flagSpec{spec: "-u --unset", description: "Removes a previously set version"},
			flagSpec{spec: "--raw", description: "Directly pipe stdin/stdout/stderr from plugin to user Sets --jobs=1"},
		},
	},
	{
		path:        []string{"shell-alias"},
		description: "Manage shell aliases.",
		flags: []flagSpec{
			flagSpec{spec: "--no-header", description: "Don't show table header"},
		},
	},
	{
		path:        []string{"shell-alias", "get"},
		description: "Show the command for a shell alias",
	},
	{
		path:        []string{"shell-alias", "ls"},
		description: "List shell aliases",
		aliases:     []string{"list"},
		flags: []flagSpec{
			flagSpec{spec: "--no-header", description: "Don't show table header"},
		},
	},
	{
		path:        []string{"shell-alias", "set"},
		description: "Add/update a shell alias",
		aliases:     []string{"add", "create"},
	},
	{
		path:        []string{"shell-alias", "unset"},
		description: "Removes a shell alias",
		aliases:     []string{"rm", "remove", "delete", "del"},
	},
	{
		path:        []string{"sync"},
		description: "Synchronize tools from other version managers with mise",
	},
	{
		path:        []string{"sync", "node"},
		description: "Symlinks all tool versions from an external tool into mise",
		flags: []flagSpec{
			flagSpec{spec: "--brew", description: "Get tool versions from Homebrew"},
			flagSpec{spec: "--nodenv", description: "Get tool versions from nodenv"},
			flagSpec{spec: "--nvm", description: "Get tool versions from nvm"},
		},
	},
	{
		path:        []string{"sync", "python"},
		description: "Symlinks all tool versions from an external tool into mise",
		flags: []flagSpec{
			flagSpec{spec: "--pyenv", description: "Get tool versions from pyenv"},
			flagSpec{spec: "--uv", description: "Sync tool versions with uv (2-way sync)"},
		},
	},
	{
		path:        []string{"sync", "ruby"},
		description: "Symlinks all ruby tool versions from an external tool into mise",
		flags: []flagSpec{
			flagSpec{spec: "--brew", description: "Get tool versions from Homebrew"},
		},
	},
	{
		path:        []string{"tasks"},
		description: "Manage tasks",
		aliases:     []string{"t", "task"},
		flags: []flagSpec{
			flagSpec{spec: "-g --global", description: "Only show global tasks", persistent: true},
			flagSpec{spec: "-J --json", description: "Output in JSON format", persistent: true},
			flagSpec{spec: "-l --local", description: "Only show non-global tasks", persistent: true},
			flagSpec{spec: "-x --extended", description: "Show all columns", persistent: true},
			flagSpec{spec: "--all", description: "Load all tasks from the entire monorepo, including sibling directories.\\nBy default, only tasks from the current directory hierarchy are loaded.", persistent: true},
			flagSpec{spec: "--hidden", description: "Show hidden tasks", persistent: true},
			flagSpec{spec: "--name-only", description: "Only show task names, one per line. Useful for piping to fzf and similar tools.", persistent: true},
			flagSpec{spec: "--no-header", description: "Do not print table header", persistent: true},
			flagSpec{spec: "--sort", description: "Sort by column. Default is name.", value: true, persistent: true, choices: []string{"name", "alias", "description", "source"}},
			flagSpec{spec: "--sort-order", description: "Sort order. Default is asc.", value: true, persistent: true, choices: []string{"asc", "desc"}},
		},
	},
	{
		path:        []string{"tasks", "add"},
		description: "Create a new task",
		flags: []flagSpec{
			flagSpec{spec: "-a --alias", description: "Other names for the task", value: true, array: true},
			flagSpec{spec: "-d --depends", description: "Add dependencies to the task", value: true, array: true},
			flagSpec{spec: "-D --dir", description: "Run the task in a specific directory", value: true},
			flagSpec{spec: "-f --file", description: "Create a file task instead of a toml task"},
			flagSpec{spec: "-H --hide", description: "Hide the task from `mise tasks` and completions"},
			flagSpec{spec: "-q --quiet", description: "Do not print the command before running"},
			flagSpec{spec: "-r --raw", description: "Directly connect stdin/stdout/stderr"},
			flagSpec{spec: "-s --sources", description: "Glob patterns of files this task uses as input", value: true, array: true},
			flagSpec{spec: "-w --wait-for", description: "Wait for these tasks to complete if they are to run", value: true, array: true},
			flagSpec{spec: "--depends-post", description: "Dependencies to run after the task runs", value: true, array: true},
			flagSpec{spec: "--description", description: "Description of the task", value: true},
			flagSpec{spec: "--outputs", description: "Glob patterns of files this task creates, to skip if they are not modified", value: true, array: true},
			flagSpec{spec: "--run-windows", description: "Command to run on windows", value: true},
			flagSpec{spec: "--shell", description: "Run the task in a specific shell", value: true},
			flagSpec{spec: "--silent", description: "Do not print the command or its output"},
		},
	},
	{
		path:        []string{"tasks", "deps"},
		description: "Display a tree visualization of a dependency graph",
		flags: []flagSpec{
			flagSpec{spec: "--dot", description: "Display dependencies in DOT format"},
			flagSpec{spec: "--hidden", description: "Show hidden tasks"},
		},
	},
	{
		path:        []string{"tasks", "edit"},
		description: "Edit a task with $EDITOR",
		flags: []flagSpec{
			flagSpec{spec: "-p --path", description: "Display the path to the task instead of editing it"},
		},
	},
	{
		path:        []string{"tasks", "info"},
		description: "Get information about a task",
		flags: []flagSpec{
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
		},
	},
	{
		path:        []string{"tasks", "ls"},
		description: "List available tasks to execute\\nThese may be included from the config file or from the project's .mise/tasks directory\\nmise will merge all tasks from all parent directories into this list.",
		flags: []flagSpec{
			flagSpec{spec: "-g --global", description: "Only show global tasks", persistent: true},
			flagSpec{spec: "-J --json", description: "Output in JSON format", persistent: true},
			flagSpec{spec: "-l --local", description: "Only show non-global tasks", persistent: true},
			flagSpec{spec: "-x --extended", description: "Show all columns", persistent: true},
			flagSpec{spec: "--all", description: "Load all tasks from the entire monorepo, including sibling directories.\\nBy default, only tasks from the current directory hierarchy are loaded.", persistent: true},
			flagSpec{spec: "--hidden", description: "Show hidden tasks", persistent: true},
			flagSpec{spec: "--name-only", description: "Only show task names, one per line. Useful for piping to fzf and similar tools.", persistent: true},
			flagSpec{spec: "--no-header", description: "Do not print table header", persistent: true},
			flagSpec{spec: "--sort", description: "Sort by column. Default is name.", value: true, persistent: true, choices: []string{"name", "alias", "description", "source"}},
			flagSpec{spec: "--sort-order", description: "Sort order. Default is asc.", value: true, persistent: true, choices: []string{"asc", "desc"}},
		},
	},
	{
		path:        []string{"tasks", "run"},
		description: "Run task(s)",
		aliases:     []string{"r"},
		flags: []flagSpec{
			flagSpec{spec: "-c --continue-on-error", description: "Continue running tasks even if one fails"},
			flagSpec{spec: "-C --cd", description: "Change to this directory before executing the command", value: true},
			flagSpec{spec: "-f --force", description: "Force the tasks to run even if outputs are up to date"},
			flagSpec{spec: "-j --jobs", description: "Number of tasks to run in parallel\\n[default: 4]\\nConfigure with `jobs` config or `MISE_JOBS` env var", value: true},
			flagSpec{spec: "-n --dry-run", description: "Don't actually run the task(s), just print them in order of execution"},
			flagSpec{spec: "-o --output", description: "Change how tasks information is output when running tasks", value: true},
			flagSpec{spec: "-q --quiet", description: "Don't show extra output"},
			flagSpec{spec: "-r --raw", description: "Read/write directly to stdin/stdout/stderr instead of by line\\nRedactions are not applied with this option\\nConfigure with `raw` config or `MISE_RAW` env var"},
			flagSpec{spec: "-s --shell", description: "Shell to use to run toml tasks", value: true},
			flagSpec{spec: "-S --silent", description: "Don't show any output except for errors"},
			flagSpec{spec: "-t --tool", description: "Tool(s) to run in addition to what is in mise.toml files e.g.: node@20 python@3.10", value: true, array: true},
			flagSpec{spec: "--allow-env", description: "[experimental] Allow specific env var through (implies --deny-env for everything else)\\nSupports wildcards, e.g. --allow-env='MYAPP_*'", value: true, array: true},
			flagSpec{spec: "--allow-net", description: "[experimental] Allow network to specific host (implies --deny-net for everything else)", value: true, array: true},
			flagSpec{spec: "--allow-read", description: "[experimental] Allow reads from specific path (implies --deny-read for everything else)", value: true, array: true},
			flagSpec{spec: "--allow-write", description: "[experimental] Allow writes to specific path (implies --deny-write for everything else)", value: true, array: true},
			flagSpec{spec: "--deny-all", description: "[experimental] Block reads, writes, network, and env vars"},
			flagSpec{spec: "--deny-env", description: "[experimental] Block env var inheritance (only PATH, HOME, USER, SHELL, TERM, LANG pass through)"},
			flagSpec{spec: "--deny-net", description: "[experimental] Block all network access"},
			flagSpec{spec: "--deny-read", description: "[experimental] Block filesystem reads (system libs and tool dirs still accessible)"},
			flagSpec{spec: "--deny-write", description: "[experimental] Block all filesystem writes"},
			flagSpec{spec: "--fresh-env", description: "Bypass the environment cache and recompute the environment"},
			flagSpec{spec: "--no-cache", description: "Do not use cache on remote tasks"},
			flagSpec{spec: "--no-deps", description: "Skip automatic dependency preparation"},
			flagSpec{spec: "--no-timings", description: "Hides elapsed time after each task completes"},
			flagSpec{spec: "--skip-deps", description: "Run only the specified tasks skipping all dependencies"},
			flagSpec{spec: "--skip-tools", description: "Skip installing tools before running tasks"},
			flagSpec{spec: "--timeout", description: "Timeout for the task to complete\\ne.g.: 30s, 5m", value: true},
		},
	},
	{
		path:        []string{"tasks", "validate"},
		description: "Validate tasks for common errors and issues",
		flags: []flagSpec{
			flagSpec{spec: "--errors-only", description: "Only show errors (skip warnings)"},
			flagSpec{spec: "--json", description: "Output validation results in JSON format"},
		},
	},
	{
		path:        []string{"test-tool"},
		description: "Test a tool installs and executes",
		flags: []flagSpec{
			flagSpec{spec: "-a --all", description: "Test every tool specified in registry/"},
			flagSpec{spec: "-j --jobs", description: "Number of tool tests to run in parallel\\n[default: 4]", value: true},
			flagSpec{spec: "--all-config", description: "Test all tools specified in config files"},
			flagSpec{spec: "--include-non-defined", description: "Also test tools not defined in registry/, guessing how to test it"},
			flagSpec{spec: "--raw", description: "Directly pipe stdin/stdout/stderr from plugin to user Sets --jobs=1"},
		},
	},
	{
		path:        []string{"token"},
		description: "Display git provider tokens mise will use",
	},
	{
		path:        []string{"token", "forgejo"},
		description: "Forgejo token",
		flags: []flagSpec{
			flagSpec{spec: "--unmask", description: "Show the full unmasked token"},
		},
	},
	{
		path:        []string{"token", "github"},
		description: "GitHub token",
		flags: []flagSpec{
			flagSpec{spec: "--oauth", description: "[experimental] Resolve only via the native GitHub OAuth source (cache, refresh, or device-code flow), bypassing other token sources"},
			flagSpec{spec: "--raw", description: "Print only the token value"},
			flagSpec{spec: "--unmask", description: "Show the full unmasked token"},
		},
	},
	{
		path:        []string{"token", "gitlab"},
		description: "GitLab token",
		flags: []flagSpec{
			flagSpec{spec: "--unmask", description: "Show the full unmasked token"},
		},
	},
	{
		path:        []string{"tool"},
		description: "Gets information about a tool",
		flags: []flagSpec{
			flagSpec{spec: "-J --json", description: "Output in JSON format"},
			flagSpec{spec: "--active", description: "Only show active versions"},
			flagSpec{spec: "--backend", description: "Only show backend field"},
			flagSpec{spec: "--config-source", description: "Only show config source"},
			flagSpec{spec: "--description", description: "Only show description field"},
			flagSpec{spec: "--installed", description: "Only show installed versions"},
			flagSpec{spec: "--requested", description: "Only show requested versions"},
			flagSpec{spec: "--tool-options", description: "Only show tool options"},
		},
	},
	{
		path:        []string{"tool-stub"},
		description: "Execute a tool stub",
	},
	{
		path:        []string{"trust"},
		description: "Marks a config file as trusted",
		flags: []flagSpec{
			flagSpec{spec: "-a --all", description: "Trust all config files in the current directory and its parents"},
			flagSpec{spec: "--ignore", description: "Do not trust this config and ignore it in the future"},
			flagSpec{spec: "--show", description: "Show the trusted status of config files from the current directory and its parents.\\nDoes not trust or untrust any files."},
			flagSpec{spec: "--untrust", description: "No longer trust this config, will prompt in the future"},
		},
	},
	{
		path:        []string{"uninstall"},
		description: "Removes installed tool versions",
		flags: []flagSpec{
			flagSpec{spec: "-a --all", description: "Delete all installed versions"},
			flagSpec{spec: "-n --dry-run", description: "Do not actually delete anything"},
			flagSpec{spec: "--dry-run-code", description: "Like --dry-run but exits with code 1 if there are tools to uninstall"},
		},
	},
	{
		path:        []string{"unset"},
		description: "Remove environment variable(s) from the config file.",
		flags: []flagSpec{
			flagSpec{spec: "-f --file", description: "Specify a file to use instead of `mise.toml`", value: true},
			flagSpec{spec: "-g --global", description: "Use the global config file"},
		},
	},
	{
		path:        []string{"untrust"},
		description: "No longer trust a config, will prompt in the future",
	},
	{
		path:        []string{"unuse"},
		description: "Removes installed tool versions from mise.toml",
		aliases:     []string{"rm", "remove"},
		flags: []flagSpec{
			flagSpec{spec: "-e --env", description: "Create/modify an environment-specific config file like .mise.<env>.toml", value: true},
			flagSpec{spec: "-g --global", description: "Use the global config file (`~/.config/mise/config.toml`) instead of the local one"},
			flagSpec{spec: "-p --path", description: "Specify a path to a config file or directory", value: true},
			flagSpec{spec: "--no-prune", description: "Do not also prune the installed version"},
		},
	},
	{
		path:        []string{"upgrade"},
		description: "Upgrades outdated tools",
		aliases:     []string{"up"},
		flags: []flagSpec{
			flagSpec{spec: "-i --interactive", description: "Display multiselect menu to choose which tools to upgrade"},
			flagSpec{spec: "-j --jobs", description: "Number of jobs to run in parallel\\n[default: 4]", value: true},
			flagSpec{spec: "-l --bump", description: "Upgrades to the latest version available, bumping the version in mise.toml"},
			flagSpec{spec: "-n --dry-run", description: "Just print what would be done, don't actually do it"},
			flagSpec{spec: "-x --exclude", description: "Tool(s) to exclude from upgrading\\ne.g.: go python", value: true, array: true},
			flagSpec{spec: "--before", description: "Only upgrade to versions released before this date", value: true},
			flagSpec{spec: "--dry-run-code", description: "Like --dry-run but exits with code 1 if there are outdated tools"},
			flagSpec{spec: "--inactive", description: "Upgrade all tools, including installed-but-inactive tools not present in the current config"},
			flagSpec{spec: "--local", description: "Only upgrade tools defined in local config files"},
			flagSpec{spec: "--raw", description: "Directly pipe stdin/stdout/stderr from plugin to user Sets --jobs=1"},
		},
	},
	{
		path:        []string{"use"},
		description: "Installs a tool and adds the version to mise.toml.",
		aliases:     []string{"u"},
		flags: []flagSpec{
			flagSpec{spec: "-e --env", description: "Create/modify an environment-specific config file like .mise.<env>.toml", value: true},
			flagSpec{spec: "-f --force", description: "Force reinstall even if already installed"},
			flagSpec{spec: "-g --global", description: "Use the global config file (`~/.config/mise/config.toml`) instead of the local one"},
			flagSpec{spec: "-j --jobs", description: "Number of jobs to run in parallel\\n[default: 4]", value: true},
			flagSpec{spec: "-n --dry-run", description: "Perform a dry run, showing what would be installed and modified without making changes"},
			flagSpec{spec: "-p --path", description: "Specify a path to a config file or directory", value: true},
			flagSpec{spec: "--before", description: "Only install versions released before this date", value: true},
			flagSpec{spec: "--dry-run-code", description: "Like --dry-run but exits with code 1 if there are changes to make"},
			flagSpec{spec: "--fuzzy", description: "Save fuzzy version to config file"},
			flagSpec{spec: "--pin", description: "Save exact version to config file\\ne.g.: `mise use --pin node@20` will save 20.0.0 as the version\\nSet `MISE_PIN=1` to make this the default behavior"},
			flagSpec{spec: "--raw", description: "Directly pipe stdin/stdout/stderr from plugin to user Sets `--jobs=1`"},
			flagSpec{spec: "--remove", description: "Remove the plugin(s) from config file", value: true, array: true},
		},
	},
	{
		path:        []string{"version"},
		description: "Display the version of mise",
		aliases:     []string{"v"},
		flags: []flagSpec{
			flagSpec{spec: "-J --json", description: "Print the version information in JSON format"},
		},
	},
	{
		path:        []string{"watch"},
		description: "Run task(s) and watch for changes to rerun it",
		aliases:     []string{"w"},
		flags: []flagSpec{
			flagSpec{spec: "--skip-deps", description: "Run only the specified tasks skipping all dependencies"},
			flagSpec{spec: "-w --watch", description: "Watch a specific file or directory", value: true, array: true},
			flagSpec{spec: "-W --watch-non-recursive", description: "Watch a specific directory, non-recursively", value: true, array: true},
			flagSpec{spec: "-F --watch-file", description: "Watch files and directories from a file", value: true},
			flagSpec{spec: "-c --clear", description: "Clear screen before running command", value: true, choices: []string{"clear", "reset"}},
			flagSpec{spec: "-o --on-busy-update", description: "What to do when receiving events while the command is running", value: true, choices: []string{"queue", "do-nothing", "restart", "signal"}},
			flagSpec{spec: "-r --restart", description: "Restart the process if it's still running"},
			flagSpec{spec: "-s --signal", description: "Send a signal to the process when it's still running", value: true},
			flagSpec{spec: "--stop-signal", description: "Signal to send to stop the command", value: true},
			flagSpec{spec: "--stop-timeout", description: "Time to wait for the command to exit gracefully", value: true},
			flagSpec{spec: "--map-signal", description: "Translate signals from the OS to signals to send to the command", value: true, array: true},
			flagSpec{spec: "-d --debounce", description: "Time to wait for new events before taking action", value: true},
			flagSpec{spec: "--stdin-quit", description: "Exit when stdin closes"},
			flagSpec{spec: "--no-vcs-ignore", description: "Don't load gitignores"},
			flagSpec{spec: "--no-project-ignore", description: "Don't load project-local ignores"},
			flagSpec{spec: "--no-global-ignore", description: "Don't load global ignores"},
			flagSpec{spec: "--no-default-ignore", description: "Don't use internal default ignores"},
			flagSpec{spec: "--no-discover-ignore", description: "Don't discover ignore files at all"},
			flagSpec{spec: "--ignore-nothing", description: "Don't ignore anything at all"},
			flagSpec{spec: "-p --postpone", description: "Wait until first change before running command"},
			flagSpec{spec: "--delay-run", description: "Sleep before running the command", value: true},
			flagSpec{spec: "--poll", description: "Poll for filesystem changes", value: true},
			flagSpec{spec: "--shell", description: "Use a different shell", value: true},
			flagSpec{spec: "-n", description: "Shorthand for '--shell=none'"},
			flagSpec{spec: "--emit-events-to", description: "Configure event emission", value: true, choices: []string{"environment", "stdio", "file", "json-stdio", "json-file", "none"}},
			flagSpec{spec: "--only-emit-events", description: "Only emit events to stdout, run no commands"},
			flagSpec{spec: "-E --env", description: "Add env vars to the command", value: true, array: true},
			flagSpec{spec: "--wrap-process", description: "Configure how the process is wrapped", value: true, choices: []string{"group", "session", "none"}},
			flagSpec{spec: "-N --notify", description: "Alert when commands start and end"},
			flagSpec{spec: "--color", description: "When to use terminal colours", value: true, choices: []string{"auto", "always", "never"}},
			flagSpec{spec: "--timings", description: "Print how long the command took to run"},
			flagSpec{spec: "-q --quiet", description: "Don't print starting and stopping messages"},
			flagSpec{spec: "--bell", description: "Ring the terminal bell on command completion"},
			flagSpec{spec: "--project-origin", description: "Set the project origin", value: true},
			flagSpec{spec: "--workdir", description: "Set the working directory", value: true},
			flagSpec{spec: "-e --exts", description: "Filename extensions to filter to", value: true, array: true},
			flagSpec{spec: "-f --filter", description: "Filename patterns to filter to", value: true, array: true},
			flagSpec{spec: "--filter-file", description: "Files to load filters from", value: true, array: true},
			flagSpec{spec: "-J --filter-prog", description: "[experimental] Filter programs", value: true, array: true},
			flagSpec{spec: "-i --ignore", description: "Filename patterns to filter out", value: true, array: true},
			flagSpec{spec: "--ignore-file", description: "Files to load ignores from", value: true, array: true},
			flagSpec{spec: "--fs-events", description: "Filesystem events to filter to", value: true, array: true, choices: []string{"access", "create", "remove", "rename", "modify", "metadata"}},
			flagSpec{spec: "--no-meta", description: "Don't emit fs events for metadata changes"},
			flagSpec{spec: "--print-events", description: "Print events that trigger actions"},
			flagSpec{spec: "--manual", description: "Show the manual page"},
		},
	},
	{
		path:        []string{"where"},
		description: "Display the installation path for a tool",
	},
	{
		path:        []string{"which"},
		description: "Shows the path that a tool's bin points to.",
		flags: []flagSpec{
			flagSpec{spec: "-t --tool", description: "Use a specific tool@version\\ne.g.: `mise which npm --tool=node@20`", value: true},
			flagSpec{spec: "--plugin", description: "Show the plugin name instead of the path"},
			flagSpec{spec: "--version", description: "Show the version instead of the path"},
		},
	},
}
