package cmd

import (
	"github.com/carapace-sh/carapace"
	"github.com/spf13/cobra"
)

var actionCmd = &cobra.Command{
	Use:   "action",
	Short: "Run the specified mappable action",
}

func init() {
	actionCmd.AddCommand(atCmd)
	carapace.Gen(actionCmd).Standalone()

	actionCmd.Flags().BoolP("help", "h", false, "Show help for this command")
	actionCmd.Flags().StringP("match", "m", "", "The window to match")
	actionCmd.Flags().Bool("no-response", false, "Don't wait for a response indicating the success of the action")
	actionCmd.Flags().Bool("self", false, "Run the action on the window this command is run in instead of the active window")

	carapace.Gen(actionCmd).FlagCompletion(carapace.ActionMap{})

	carapace.Gen(actionCmd).PositionalAnyCompletion(
		// see https://sw.kovidgoyal.net/kitty/actions/
		carapace.ActionValuesDescribed(
			"clear_selection", "Clear the current selection.",
			"copy_and_clear_or_interrupt", "Copy the selected text from the active window to the clipboard and clear the selection; if no selection, send SIGINT.",
			"copy_ansi_to_clipboard", "Copy the selected text from the active window to the clipboard with ANSI formatting codes.",
			"copy_last_command_output", "Copy the last non-empty output from a shell command to the clipboard. Requires shell integration.",
			"copy_or_interrupt", "Copy the selected text from the active window to the clipboard; if no selection, send SIGINT.",
			"copy_or_noop", "Copy the selected text from the active window to the clipboard; if no selection, pass the key through to the application.",
			"copy_to_clipboard", "Copy the selected text from the active window to the clipboard.",
			"pass_selection_to_program", "Pass the selected text from the active window to the specified program.",
			"paste", "Paste the specified text into the current window; ANSI C escapes are decoded.",
			"search_scrollback", "Search scrollback in a pager like less; if text is selected, it is searched for. Assumes / triggers search in the configured pager.",
			"show_first_command_output_on_screen", "Show output from the first shell command on screen in a pager like less. Requires shell integration.",
			"show_last_command_output", "Show output from the last shell command in a pager like less. Requires shell integration.",
			"show_last_non_empty_command_output", "Show the last non-empty output from a shell command in a pager like less. Requires shell integration.",
			"show_last_visited_command_output", "Show the first command output below the last scrolled position via scroll_to_prompt, or the last mouse-clicked command output, in a pager like less. Requires shell integration.",
			"show_scrollback", "Show scrollback in a pager like less.",
			"copy_to_buffer", "Copy the selection from the active window to the specified buffer.",
			"paste_from_buffer", "Paste from the specified buffer to the active window.",
			"paste_from_clipboard", "Paste from the clipboard to the active window.",
			"paste_from_selection", "Paste from the primary selection if present, otherwise from the clipboard to the active window.",
			"dump_lines_with_attrs", "Show a dump of the current lines in the scrollback and screen with their line attributes.",
			"close_shared_ssh_connections", "Close all shared SSH connections.",
			"debug_config", "Show the effective configuration kitty is running with.",
			"show_kitty_env_vars", "Show the environment variables that the kitty process sees.",
			"simulate_color_scheme_preference_change", "Simulate a change in OS color scheme preference.",
			"goto_layout", "Switch to the named layout. If multiple layouts share the name, specify the full definition or a unique prefix.",
			"last_used_layout", "Go to the previously used layout.",
			"layout_action", "Perform a layout-specific action.",
			"next_layout", "Go to the next enabled layout; optionally jump by a specified number.",
			"toggle_layout", "Toggle the named layout, switching to it if another is current or back to the last used layout.",
			"remove_marker", "Remove a previously created marker.",
			"scroll_to_mark", "Scroll to the next or previous mark of the specified type.",
			"toggle_marker", "Toggle the current marker on or off.",
			"create_marker", "Create a new marker.",
			"send_key", "Send the specified keys to the active window (press and release); works only if the program’s keyboard mode supports it.",
			"send_text", "Send the specified text to the active window.",
			"show_kitty_doc", "Display the specified kitty documentation, preferring a local copy if found.",
			"signal_child", "Send the specified signal to the foreground process in the active window.",
			"clear_terminal", "Clear the terminal (various modes available; see reset_terminal for details).",
			"combine", "Combine multiple actions and map them to a single keypress.",
			"disable_ligatures_in", "Turn ligatures on or off in the specified window.",
			"discard_event", "Discard this event, ignoring it completely.",
			"edit_config_file", "Edit the kitty.conf config file in your preferred text editor.",
			"grab_keyboard", "Grab the keyboard so OS global shortcuts are passed to kitty; support depends on OS/window manager (not permitted on macOS without special permissions).",
			"hide_macos_app", "Hide the macOS kitty application.",
			"hide_macos_other_apps", "Hide other macOS applications.",
			"input_unicode_character", "Input an arbitrary Unicode character.",
			"kitten", "Run the specified kitten.",
			"kitty_shell", "Run the kitty shell to control kitty with commands.",
			"launch", "Launch the specified program in a new window, tab, etc.",
			"load_config_file", "Reload the config file; without arguments reloads the default, otherwise loads specified files and replaces all options.",
			"macos_cycle_through_os_windows", "Cycle through OS windows on macOS.",
			"macos_cycle_through_os_windows_backwards", "Cycle backwards through OS windows on macOS.",
			"minimize_macos_window", "Minimize the macOS window.",
			"open_url", "Open the specified URL.",
			"open_url_with_hints", "Click a URL using the keyboard.",
			"pop_keyboard_mode", "End the current keyboard mode and switch to the previous mode.",
			"push_keyboard_mode", "Switch to the specified keyboard mode, pushing it onto the stack.",
			"remote_control", "Run a remote control command without needing to allow remote control.",
			"remote_control_script", "Run a remote control script without needing to allow remote control.",
			"set_colors", "Change colors in the specified windows.",
			"show_error", "Show an error message with the specified title and text.",
			"sleep", "Sleep for a specified duration; supports s, m, h, d suffixes and fractional times.",
			"toggle_macos_secure_keyboard_entry", "Toggle macOS secure keyboard entry.",
			"ungrab_keyboard", "Ungrab the keyboard if it was previously grabbed.",
			"no_op", "Unbind a shortcut so the keystroke is passed to the application.",
			"mouse_click_url", "Click the URL under the mouse.",
			"mouse_click_url_or_select", "Click the URL under the mouse only if there is no selection on the screen.",
			"mouse_handle_click", "Handle a mouse click by trying actions in order until one succeeds: selection, link, prompt.",
			"mouse_select_command_output", "Select the clicked command output. Requires shell integration.",
			"mouse_selection", "Manipulate the selection based on the current mouse position.",
			"mouse_show_command_output", "Show clicked command output in a pager like less. Requires shell integration.",
			"paste_selection", "Paste the current primary selection.",
			"paste_selection_or_clipboard", "Paste the current primary selection or the clipboard if no selection is present.",
			"scroll_end", "Scroll to the bottom of the scrollback buffer when in the main screen.",
			"scroll_home", "Scroll to the top of the scrollback buffer when in the main screen.",
			"scroll_line_down", "Scroll down by one line when in the main screen.",
			"scroll_line_up", "Scroll up by one line when in the main screen.",
			"scroll_page_down", "Scroll down by one page when in the main screen.",
			"scroll_page_up", "Scroll up by one page when in the main screen.",
			"scroll_prompt_to_bottom", "Scroll the prompt to the bottom of the screen, filling extra lines from the scrollback, when in the main screen.",
			"scroll_prompt_to_top", "Scroll the prompt to the top of the screen, filling the screen with empty lines, when in the main screen; optionally avoid moving lines above the prompt into scrollback.",
			"scroll_to_prompt", "Scroll to the previous or next shell command prompt; supports optional count and context lines. Requires shell integration.",
			"close_session", "Close a session (close all windows that belong to the session).",
			"goto_session", "Switch to the specified session, creating it if not already present.",
			"save_as_session", "Save the current kitty state as a session file.",
			"close_other_tabs_in_os_window", "Close all tabs in the current OS window except the active tab.",
			"close_tab", "Close the current tab.",
			"detach_tab", "Detach a tab, moving it to another OS window.",
			"goto_tab", "Go to the specified tab by number (starting at 1); zero or negative numbers go to previously active tabs.",
			"move_tab_backward", "Move the active tab backward.",
			"move_tab_forward", "Move the active tab forward.",
			"new_tab", "Create a new tab.",
			"new_tab_with_cwd", "Create a new tab with the working directory set to that of the active window; added to the current session if any.",
			"next_tab", "Make the next tab active.",
			"previous_tab", "Make the previous tab active.",
			"select_tab", "Interactively select a tab to switch to.",
			"set_tab_title", "Change the title of the active tab interactively or set a title via argument; empty string resets; a space avoids prefill.",
			"set_window_title", "Change the title of the active window interactively or set a title via argument; empty string resets; a space avoids prefill.",
			"close_other_windows_in_tab", "Close all windows in the tab except the active window.",
			"eighth_window", "Focus the eighth window.",
			"fifth_window", "Focus the fifth window.",
			"first_window", "Focus the first window.",
			"focus_visible_window", "Focus a visible window by pressing its displayed number in visual selection mode.",
			"fourth_window", "Focus the fourth window.",
			"move_window", "Move the window in the specified direction.",
			"move_window_backward", "Move the active window backward (swap with the previous window).",
			"move_window_forward", "Move the active window forward (swap with the next window).",
			"move_window_to_top", "Move the active window to the top (make it the first window).",
			"neighboring_window", "Focus the neighboring window in the current tab.",
			"next_window", "Focus the next window in the current tab.",
			"ninth_window", "Focus the ninth window.",
			"nth_window", "Focus the nth window if positive, or previously active windows if negative; if the number exceeds the window count, focus the last window.",
			"previous_window", "Focus the previous window in the current tab.",
			"reset_window_sizes", "Reset window sizes, undoing any dynamic resizing.",
			"resize_window", "Resize the active window by the specified amount.",
			"second_window", "Focus the second window.",
			"seventh_window", "Focus the seventh window.",
			"sixth_window", "Focus the sixth window.",
			"swap_with_window", "Swap the current window with another window in the current tab, selected visually.",
			"tenth_window", "Focus the tenth window.",
			"third_window", "Focus the third window.",
			"change_font_size", "Change the font size for the current or all OS windows.",
			"close_os_window", "Close the currently active OS window.",
			"close_other_os_windows", "Close all other OS windows except the one containing the active window.",
			"close_window", "Close the currently active window.",
			"close_window_with_confirmation", "Close the window with confirmation; can ignore confirmation at a shell prompt with an option. Requires shell integration for prompt detection.",
			"detach_window", "Detach a window, moving it to another tab or OS window.",
			"new_os_window", "Create a new OS window.",
			"new_os_window_with_cwd", "Create a new OS window with the same working directory as the active window; added to the current session if any.",
			"new_window", "Create a new window.",
			"new_window_with_cwd", "Create a new window with the same working directory as the active window; added to the current session if any.",
			"nth_os_window", "Focus the nth OS window if positive or the previously active ones if negative; zero refocuses the current OS window (if the window manager allows grabbing focus).",
			"quit", "Quit kitty, closing all windows.",
			"set_background_opacity", "Set the background opacity for the active OS window (supports relative and absolute values).",
			"start_resizing_window", "Interactively resize the active window.",
			"toggle_fullscreen", "Toggle the fullscreen status of the active OS window.",
			"toggle_maximized", "Toggle the maximized status of the active OS window.",
			"toggle_tab", "Toggle to the tab matching the specified expression, or switch back to the last used tab within the same OS window.",
		),
	)
}
