package cmd

import (
	"github.com/carapace-sh/carapace"
	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "kitten",
	Short: "kitten serves as a launcher for running individual kittens",
	Long:  "https://sw.kovidgoyal.net/kitty/kittens_intro/",
	Run:   func(cmd *cobra.Command, args []string) {},
}

func Execute() error {
	return rootCmd.Execute()
}

func init() {
	carapace.Gen(rootCmd).Standalone()

	rootCmd.Flags().Bool("version", false, "The current kitten version")
	rootCmd.Flags().BoolP("help", "h", false, "Show help for this command")
}

// ⏳ @:Control kitty remotely
// ✅ update-self:Update this kitten binary
// ✅ edit-in-kitty:Edit a file in a kitty overlay window
// ✅ clipboard:Copy/paste with the system clipboard, even over SSH
// ✅ icat:Display images in the terminal
// ✅ ssh:Truly convenient SSH
// ✅ transfer:Transfer files easily over the TTY device
// ✅ panel:Use a command line program to draw a GPU accelerated panel on your desktop
// ✅ quick-access-terminal:A quick access terminal window that you can bring up instantly with a keypress or a command.
// ✅ unicode-input:Browse and select unicode characters by name
// ✅ show-key:Show the codes generated by the terminal for key presses in various keyboard modes
// ⏳ desktop-ui:Implement various desktop components for use with lightweight compositors/window managers on Linux
// ✅ mouse-demo:Demo the mouse handling kitty implements for terminal programs
// ✅ hyperlinked-grep:Add hyperlinks to the output of ripgrep
// ✅ ask:Ask the user for input
// ✅ hints:Select text from screen with keyboard
// ✅ diff:Pretty, side-by-side diffing of files and images
// ✅ notify:Send notifications to the user
// ✅ themes:Manage kitty color schemes easily
// ✅ run-shell:Run the user's shell with shell integration enabled
// ✅ choose-fonts:Choose the fonts used in kitty
// ✅ choose-files:Choose files, fast
// ✅ query-terminal:Query the terminal for various capabilities
